"""
Seed: Fundamentos de Hardware — 45 preguntas tipo test
Temas: Buses de datos, Ensamblado PC, Von Neumann, CAS, Microprocesador,
       Clasificación software, Virtualización, Almacenamiento en red, CPD/Racks,
       Alta disponibilidad.

Ejecutar desde la carpeta /backend con el venv activo:
  python seed_hardware_questions.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import SessionLocal, Question

QUESTIONS = [

    # ── BUSES DE DATOS ─────────────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál es la función principal del bus de datos en un sistema informático?",
        "option_a": "Transportar señales de control entre la CPU y los dispositivos de entrada/salida.",
        "option_b": "Transferir datos binarios entre el procesador, la memoria y los dispositivos del sistema.",
        "option_c": "Gestionar las interrupciones generadas por los periféricos conectados.",
        "option_d": "Sincronizar el reloj del sistema con los módulos de memoria RAM.",
        "correct_answer": "B",
        "explanation": "El bus de datos es el canal por el que se transfieren los datos entre la CPU, la memoria RAM y los periféricos. Su anchura (8, 16, 32, 64 bits) determina cuántos bits se pueden transmitir simultáneamente.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué diferencia principal existe entre el bus de datos y el bus de direcciones?",
        "option_a": "El bus de datos transporta únicamente instrucciones, mientras que el bus de direcciones transporta los operandos.",
        "option_b": "El bus de datos es bidireccional y transfiere información, mientras que el bus de direcciones es unidireccional e indica la ubicación de memoria a la que se accede.",
        "option_c": "El bus de direcciones tiene mayor anchura que el bus de datos en todos los procesadores modernos.",
        "option_d": "Ambos buses son idénticos en función; la diferencia es únicamente de nomenclatura según el fabricante.",
        "correct_answer": "B",
        "explanation": "El bus de datos es bidireccional (lectura y escritura) y transporta los datos. El bus de direcciones es unidireccional (solo desde la CPU) e indica la dirección de memoria o del dispositivo con el que se quiere comunicar.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "Un sistema tiene un bus de direcciones de 32 bits. ¿Cuánta memoria RAM puede direccionar como máximo?",
        "option_a": "2 GB",
        "option_b": "4 GB",
        "option_c": "8 GB",
        "option_d": "16 GB",
        "correct_answer": "B",
        "explanation": "Con 32 bits de direcciones se pueden referenciar 2³² posiciones de memoria = 4.294.967.296 bytes = 4 GB. Esta fue la limitación de los sistemas x86 de 32 bits, que no podían usar más de 4 GB de RAM.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Qué bus se encarga de transmitir señales de control como lectura/escritura y habilitación de dispositivos?",
        "option_a": "Bus de datos",
        "option_b": "Bus de direcciones",
        "option_c": "Bus de control",
        "option_d": "Bus PCI Express",
        "correct_answer": "C",
        "explanation": "El bus de control transmite señales que coordinan las operaciones del sistema: lectura/escritura, habilitación de dispositivos, señales de reloj e interrupciones. Junto con el bus de datos y el de direcciones, forma el bus del sistema.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál de las siguientes interfaces de bus ofrece mayor ancho de banda para tarjetas gráficas modernas?",
        "option_a": "ISA (Industry Standard Architecture)",
        "option_b": "PCI convencional de 32 bits",
        "option_c": "AGP (Accelerated Graphics Port)",
        "option_d": "PCIe x16 (PCI Express x16)",
        "correct_answer": "D",
        "explanation": "PCI Express x16 es el estándar actual para tarjetas gráficas de alto rendimiento, ofreciendo velocidades de transferencia de hasta 64 GB/s (PCIe 5.0). Sustituye a ISA, PCI y AGP que tenían anchos de banda muy inferiores.",
    },

    # ── ENSAMBLADO DE PC ───────────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "Al instalar un procesador en su socket, ¿cuál es el paso más importante para garantizar una instalación correcta?",
        "option_a": "Aplicar una gruesa capa de pasta térmica antes de insertar el procesador.",
        "option_b": "Alinear correctamente la muesca o triángulo indicador del procesador con el del socket antes de colocarlo.",
        "option_c": "Presionar firmemente el procesador hasta escuchar un clic que confirme el encaje.",
        "option_d": "Humedecer ligeramente los pines del socket para facilitar la inserción.",
        "correct_answer": "B",
        "explanation": "La alineación mediante la muesca o el triángulo indicador (presente tanto en el procesador como en el socket) es fundamental. Forzar el procesador sin la orientación correcta puede doblar o romper los pines, inutilizando el procesador o la placa base.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Por qué es fundamental conectarse a tierra (descarga electrostática) antes de manipular componentes internos de un PC?",
        "option_a": "Para evitar que el calor corporal dañe los chips de memoria.",
        "option_b": "Para prevenir que la electricidad estática del cuerpo descargue sobre los circuitos integrados y los dañe.",
        "option_c": "Para que los conectores de alimentación encajen correctamente en sus ranuras.",
        "option_d": "Para reiniciar la BIOS antes de instalar nuevos componentes.",
        "correct_answer": "B",
        "explanation": "La electricidad estática acumulada en el cuerpo puede dañar permanentemente los circuitos integrados sensibles. Se recomienda usar pulsera antiestática conectada a tierra o tocar una parte metálica del chasis conectado a la red eléctrica antes de manipular componentes.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "Al instalar módulos de RAM en una placa base con soporte Dual Channel, ¿cómo se deben colocar correctamente?",
        "option_a": "En cualquier par de ranuras contiguas, ya que el Dual Channel se activa automáticamente.",
        "option_b": "En los slots indicados por el fabricante como emparejados, normalmente ranuras del mismo color o etiquetadas A1-B1 o A2-B2.",
        "option_c": "Siempre en las dos primeras ranuras más cercanas al procesador para minimizar la latencia.",
        "option_d": "En ranuras alternas, dejando siempre una ranura vacía entre cada módulo instalado.",
        "correct_answer": "B",
        "explanation": "Para activar el modo Dual Channel se deben instalar los módulos en las ranuras emparejadas que indica el fabricante (generalmente del mismo color). Colocarlos en ranuras incorrectas hará que funcionen en modo Single Channel, reduciendo el ancho de banda de memoria a la mitad.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Cuál es la función de la pasta térmica al instalar el disipador sobre el procesador?",
        "option_a": "Actuar como adhesivo permanente para fijar el disipador al procesador.",
        "option_b": "Mejorar la conducción de calor entre la tapa del procesador y la base del disipador, eliminando microhuecos de aire.",
        "option_c": "Proteger el procesador de daños mecánicos durante la instalación del disipador.",
        "option_d": "Proporcionar un aislamiento eléctrico entre el procesador y el sistema de refrigeración.",
        "correct_answer": "B",
        "explanation": "La pasta térmica (o compuesto térmico) rellena las microirregularidades entre la superficie del procesador y la base del disipador. El aire es mal conductor de calor, por lo que la pasta mejora significativamente la transferencia térmica y evita el sobrecalentamiento del CPU.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "Al ensamblar un PC, el sistema enciende pero no muestra imagen y emite una serie de pitidos. ¿Qué indica este comportamiento?",
        "option_a": "El sistema operativo no está instalado correctamente en el disco duro.",
        "option_b": "La BIOS/UEFI ha detectado un error de hardware durante el POST y los pitidos son un código de error específico.",
        "option_c": "El monitor no está correctamente conectado a la tarjeta gráfica.",
        "option_d": "La fuente de alimentación no suministra suficiente voltaje al procesador.",
        "correct_answer": "B",
        "explanation": "Durante el POST (Power-On Self Test), la BIOS/UEFI realiza una comprobación del hardware. Si detecta un error antes de poder mostrar imagen, emite una secuencia de pitidos que es un código de diagnóstico. Cada fabricante tiene su propia tabla de códigos de pitido para identificar el componente con fallo (RAM, GPU, CPU, etc.).",
    },

    # ── MODELO VON NEUMANN ─────────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Cuál es la característica principal que define la arquitectura de Von Neumann?",
        "option_a": "Utiliza procesadores independientes para datos e instrucciones, ejecutándolos en paralelo.",
        "option_b": "Los datos y los programas se almacenan en la misma memoria, compartiendo el mismo bus para acceder a ellos.",
        "option_c": "Separa físicamente la memoria de instrucciones de la memoria de datos en bancos independientes.",
        "option_d": "Requiere que todos los programas sean cargados en la memoria ROM antes de su ejecución.",
        "correct_answer": "B",
        "explanation": "La arquitectura Von Neumann (1945) define que tanto los datos como las instrucciones del programa se almacenan en la misma memoria principal, compartiendo el mismo bus del sistema. Esto genera el 'cuello de botella de Von Neumann', ya que el procesador no puede leer instrucciones y datos simultáneamente.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué unidad de la arquitectura Von Neumann se encarga de ejecutar las operaciones aritméticas y lógicas?",
        "option_a": "Unidad de Control (UC)",
        "option_b": "Unidad Aritmético-Lógica (ALU)",
        "option_c": "Unidad de Memoria Principal",
        "option_d": "Registro de Instrucciones (IR)",
        "correct_answer": "B",
        "explanation": "La ALU (Arithmetic Logic Unit) es el componente del procesador que realiza todas las operaciones aritméticas (suma, resta, multiplicación, división) y lógicas (AND, OR, NOT, XOR, comparaciones). La Unidad de Control, en cambio, dirige y coordina el funcionamiento del resto de componentes.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "En el ciclo de instrucción de Von Neumann, ¿qué fase sigue inmediatamente después de la fase de búsqueda (Fetch)?",
        "option_a": "Escritura (Write-Back)",
        "option_b": "Ejecución (Execute)",
        "option_c": "Decodificación (Decode)",
        "option_d": "Almacenamiento (Store)",
        "correct_answer": "C",
        "explanation": "El ciclo de instrucción clásico es: Fetch (búsqueda de la instrucción en memoria) → Decode (decodificación de la instrucción por la Unidad de Control) → Execute (ejecución por la ALU). En arquitecturas modernas se añaden etapas adicionales como Fetch de operandos y Write-Back.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿En qué se diferencia la arquitectura Harvard de la arquitectura Von Neumann?",
        "option_a": "Harvard utiliza un único bus compartido para datos e instrucciones, mientras que Von Neumann usa buses separados.",
        "option_b": "Harvard dispone de memorias y buses físicamente separados para instrucciones y datos, permitiendo acceder a ambos simultáneamente.",
        "option_c": "Harvard es exclusiva de microcontroladores, mientras que Von Neumann solo se usa en supercomputadores.",
        "option_d": "Harvard no tiene Unidad de Control, mientras que Von Neumann sí la incluye como elemento central.",
        "correct_answer": "B",
        "explanation": "La arquitectura Harvard utiliza memorias y buses físicamente separados para instrucciones y datos. Esto elimina el cuello de botella de Von Neumann al permitir que el procesador acceda simultáneamente a instrucciones y datos. Se usa ampliamente en microcontroladores (PIC, AVR) y en cachés modernas de CPU (L1I y L1D separadas).",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Cuál de los siguientes componentes NO forma parte de la arquitectura Von Neumann original?",
        "option_a": "Unidad Central de Proceso (CPU)",
        "option_b": "Memoria Principal",
        "option_c": "Dispositivos de Entrada/Salida",
        "option_d": "Caché L3 compartida entre núcleos",
        "correct_answer": "D",
        "explanation": "El modelo Von Neumann original define: CPU (con ALU y Unidad de Control), Memoria Principal, y Dispositivos de E/S conectados por buses. La caché L3 compartida es una evolución tecnológica posterior introducida en procesadores multi-núcleo modernos para reducir el cuello de botella de memoria.",
    },

    # ── CAS / SEÑALIZADOR DE DIRECCIONAMIENTO ──────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "En memorias DRAM, ¿qué significa la señal CAS (Column Address Strobe)?",
        "option_a": "Es la señal que indica al módulo de memoria que debe realizar una operación de actualización (refresh) del contenido.",
        "option_b": "Es la señal que indica que la dirección presente en el bus corresponde a la columna de la celda de memoria a la que se quiere acceder.",
        "option_c": "Es la señal que habilita la comunicación entre la CPU y el controlador de memoria integrado.",
        "option_d": "Es la señal que determina el voltaje de operación del módulo de RAM durante el acceso.",
        "correct_answer": "B",
        "explanation": "En DRAM, la memoria está organizada como una matriz de filas y columnas. Para acceder a una celda, primero se envía la dirección de fila con la señal RAS (Row Address Strobe) y luego la dirección de columna con la señal CAS (Column Address Strobe). La latencia CAS (CL) indica cuántos ciclos de reloj tarda en responder tras recibir la dirección de columna.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿Qué representa la latencia CAS (CL) en las especificaciones de un módulo de RAM DDR4?",
        "option_a": "El número de canales de datos simultáneos que puede manejar el módulo.",
        "option_b": "El número de ciclos de reloj que transcurren entre que el controlador envía la dirección de columna y el módulo entrega el dato solicitado.",
        "option_c": "La capacidad máxima de memoria en gigabytes que puede albergar el módulo.",
        "option_d": "La temperatura máxima de operación expresada en décimas de grado Celsius.",
        "correct_answer": "B",
        "explanation": "La latencia CAS (Column Access Strobe Latency, CL) es uno de los parámetros más importantes de la RAM. Indica el número de ciclos de reloj que el módulo tarda en responder tras recibir la dirección de columna. Un CL14 a 3200 MHz tiene una latencia real de 14/3200M ≈ 8,75 ns, mientras que un CL16 a 3600 MHz sería 16/3600M ≈ 8,88 ns.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "En las especificaciones de RAM '16-18-18-38', ¿qué representa el primer número (16)?",
        "option_a": "La frecuencia de operación en MHz",
        "option_b": "La latencia CAS (CL), es decir, los ciclos de reloj de retardo en el acceso a columna",
        "option_c": "La capacidad del módulo en gigabytes",
        "option_d": "El voltaje de operación multiplicado por 10",
        "correct_answer": "B",
        "explanation": "Los cuatro números en las especificaciones de RAM (ej. 16-18-18-38) representan los timings: CL (CAS Latency), tRCD (RAS to CAS Delay), tRP (RAS Precharge) y tRAS (Row Active Time) respectivamente. El primer número, CL=16, es la latencia CAS, el timing más relevante para el rendimiento general.",
    },

    # ── CARACTERÍSTICAS DEL MICROPROCESADOR ────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Qué determina principalmente la frecuencia de reloj de un microprocesador?",
        "option_a": "La cantidad de memoria caché disponible en el chip.",
        "option_b": "El número de operaciones (ciclos) que el procesador puede realizar por segundo.",
        "option_c": "El número de núcleos físicos integrados en el procesador.",
        "option_d": "La cantidad de memoria RAM máxima que el procesador puede direccionar.",
        "correct_answer": "B",
        "explanation": "La frecuencia de reloj (medida en GHz) indica el número de ciclos por segundo que puede ejecutar el procesador. A mayor frecuencia, más operaciones por segundo en un mismo núcleo. Sin embargo, no es el único factor de rendimiento; también influyen la arquitectura, el IPC (instrucciones por ciclo) y el número de núcleos.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué ventaja principal ofrecen los procesadores multi-núcleo frente a los mono-núcleo de mayor frecuencia?",
        "option_a": "Permiten ejecutar más rápido un único hilo de programa gracias a la mayor frecuencia por núcleo.",
        "option_b": "Permiten ejecutar múltiples tareas o hilos en paralelo de forma real, mejorando el rendimiento en cargas de trabajo multihilo.",
        "option_c": "Reducen el consumo eléctrico total del sistema al repartir la carga entre varios núcleos de baja potencia.",
        "option_d": "Eliminan la necesidad de memoria caché al disponer de acceso directo a la RAM desde cada núcleo.",
        "correct_answer": "B",
        "explanation": "Los procesadores multi-núcleo permiten la ejecución paralela real de múltiples hilos de ejecución. Esto mejora significativamente el rendimiento en aplicaciones multihilo como renderizado, compilación, edición de vídeo o virtualización, donde mono-núcleos de alta frecuencia tienen limitaciones físicas.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál es la función principal de la memoria caché integrada en un microprocesador?",
        "option_a": "Almacenar permanentemente el sistema operativo para acelerar el arranque del equipo.",
        "option_b": "Reducir el tiempo de acceso a datos e instrucciones frecuentes, almacenando copias de la RAM más cercanas al núcleo de proceso.",
        "option_c": "Gestionar la comunicación entre el procesador y los dispositivos de almacenamiento secundario.",
        "option_d": "Ampliar la memoria virtual disponible cuando la RAM física está completa.",
        "correct_answer": "B",
        "explanation": "La caché del procesador (L1, L2, L3) es una memoria SRAM ultrarrápida integrada en el chip que almacena copias de los datos e instrucciones más utilizados recientemente. Al estar físicamente en el chip, el acceso es varios órdenes de magnitud más rápido que acceder a la RAM, reduciendo el cuello de botella de memoria.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿Qué es el TDP (Thermal Design Power) de un procesador?",
        "option_a": "La potencia máxima absoluta que puede consumir el procesador en condiciones de carga extrema.",
        "option_b": "La potencia máxima de calor que el sistema de refrigeración debe ser capaz de disipar para mantener el procesador en rango de temperatura normal bajo carga sostenida.",
        "option_c": "La eficiencia energética del procesador medida en instrucciones por vatio consumido.",
        "option_d": "El voltaje base de operación del procesador multiplicado por su consumo máximo de corriente.",
        "correct_answer": "B",
        "explanation": "El TDP (Thermal Design Power) es la cantidad máxima de calor (en vatios) que el sistema de refrigeración debe ser capaz de disipar para mantener el procesador operando dentro de su rango térmico seguro bajo carga típica sostenida. No es el consumo máximo absoluto, sino el valor de referencia para dimensionar el sistema de refrigeración.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué indica el proceso de fabricación de un microprocesador (expresado en nanómetros)?",
        "option_a": "El tamaño físico total del chip en milímetros cuadrados.",
        "option_b": "El tamaño de los transistores y la distancia entre ellos; a menor nanómetro, más transistores por área, mayor rendimiento y menor consumo.",
        "option_c": "La velocidad máxima del bus frontal (FSB) que el procesador puede utilizar.",
        "option_d": "El número de capas de metal de interconexión utilizadas en la fabricación del chip.",
        "correct_answer": "B",
        "explanation": "El nodo de proceso (en nm) indica el tamaño de los transistores del chip. A menor tamaño, se pueden integrar más transistores en la misma área de silicio, lo que permite mayor rendimiento, eficiencia energética y menor disipación de calor. Por ejemplo, pasar de 14 nm a 7 nm aproximadamente dobla la densidad de transistores.",
    },

    # ── CLASIFICACIÓN TIPO DE SOFTWARE ─────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Cuál de las siguientes categorías corresponde correctamente a la clasificación del software?",
        "option_a": "Software libre, software de pago y software de código abierto son tres categorías completamente independientes sin ninguna relación entre sí.",
        "option_b": "El software se clasifica principalmente en software de sistema (SO, drivers, utilidades) y software de aplicación (programas de usuario).",
        "option_c": "Todo el software puede clasificarse exclusivamente según su precio: gratuito, freemium o de pago.",
        "option_d": "La única clasificación válida del software es según el lenguaje de programación usado para desarrollarlo.",
        "correct_answer": "B",
        "explanation": "La clasificación principal del software diferencia entre software de sistema (que gestiona el hardware y proporciona servicios base: sistema operativo, controladores, firmware, utilidades) y software de aplicación (que realiza tareas específicas para el usuario: procesadores de texto, navegadores, videojuegos). También existe el software de programación (compiladores, IDEs).",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál de las siguientes opciones define correctamente el software propietario?",
        "option_a": "Software cuyo código fuente es accesible y modificable por cualquier desarrollador que lo desee.",
        "option_b": "Software cuya distribución, modificación y uso están restringidos por el titular de los derechos, que mantiene el código fuente privado.",
        "option_c": "Software que puede usarse gratuitamente pero no puede ser distribuido ni modificado bajo ninguna circunstancia.",
        "option_d": "Software que pertenece a organismos públicos y cuya licencia obliga a cederlo a todos los ciudadanos.",
        "correct_answer": "B",
        "explanation": "El software propietario (o privativo) es aquel en el que el titular de los derechos (empresa o desarrollador) mantiene el código fuente privado y restringe el uso, copia, distribución y modificación. El usuario obtiene una licencia de uso pero no derechos sobre el código. Ejemplos: Microsoft Windows, Adobe Photoshop.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué característica distingue al software libre del software simplemente gratuito (freeware)?",
        "option_a": "El software libre siempre tiene un coste económico, mientras que el freeware es gratuito.",
        "option_b": "El software libre garantiza las libertades de uso, estudio, modificación y distribución, independientemente de si tiene coste; el freeware solo garantiza la gratuidad.",
        "option_c": "El freeware incluye el código fuente y puede ser modificado, mientras que el software libre no.",
        "option_d": "El software libre solo puede usarse en sistemas operativos Linux, mientras que el freeware es multiplataforma.",
        "correct_answer": "B",
        "explanation": "El software libre (definido por la FSF) garantiza cuatro libertades: usar, estudiar, modificar y distribuir el software. Puede ser gratuito o de pago. El freeware simplemente se distribuye sin coste económico, pero el fabricante puede mantener el código cerrado y restringir modificaciones. GNU/Linux, LibreOffice y VLC son software libre.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿A qué tipo de software pertenecen los controladores de dispositivos (drivers)?",
        "option_a": "Software de aplicación",
        "option_b": "Software de programación",
        "option_c": "Software de sistema",
        "option_d": "Software de virtualización",
        "correct_answer": "C",
        "explanation": "Los drivers o controladores de dispositivos son software de sistema que actúan de intermediarios entre el sistema operativo y el hardware (impresoras, tarjetas gráficas, tarjetas de red, etc.). Permiten que el SO interactúe con dispositivos sin necesitar conocer su funcionamiento interno específico.",
    },

    # ── VIRTUALIZACIÓN ─────────────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué ventaja clave ofrecen las técnicas de virtualización en la instalación y prueba de aplicaciones?",
        "option_a": "Permite el funcionamiento de la aplicación sin necesidad de cumplir con los requisitos mínimos de hardware del sistema.",
        "option_b": "Facilita la creación de un ambiente virtual aislado que funciona como una máquina independiente para instalar y ejecutar software.",
        "option_c": "Reduce significativamente la necesidad de actualizaciones y parches de seguridad para las aplicaciones instaladas.",
        "option_d": "Duplica automáticamente el rendimiento del hardware físico disponible.",
        "correct_answer": "B",
        "explanation": "La virtualización permite crear máquinas virtuales (VM) que funcionan como equipos independientes dentro de un host físico. Esto facilita instalar y probar software en entornos aislados sin afectar al sistema anfitrión, probar configuraciones con diferentes sistemas operativos y revertir cambios fácilmente mediante snapshots.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué es un hipervisor y cuál es su función en la virtualización?",
        "option_a": "Un hipervisor es un tipo de procesador diseñado específicamente para ejecutar máquinas virtuales a mayor velocidad.",
        "option_b": "Es el software o firmware que gestiona y abstrae los recursos del hardware físico, permitiendo que múltiples máquinas virtuales se ejecuten simultáneamente sobre él.",
        "option_c": "Es un protocolo de red que permite la comunicación entre máquinas virtuales en diferentes servidores físicos.",
        "option_d": "Es una utilidad del sistema operativo que optimiza el uso de la memoria RAM entre aplicaciones.",
        "correct_answer": "B",
        "explanation": "El hipervisor (VMM, Virtual Machine Monitor) es el componente central de la virtualización. Gestiona el acceso de las máquinas virtuales al hardware físico (CPU, RAM, almacenamiento, red). Existen hipervisores Tipo 1 (bare-metal, como VMware ESXi o Hyper-V) que corren directamente sobre el hardware, y Tipo 2 (hosted, como VirtualBox o VMware Workstation) que corren sobre un SO anfitrión.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿En qué se diferencia la virtualización por contenedores (Docker) de la virtualización de máquinas virtuales completas?",
        "option_a": "Los contenedores virtualizan el hardware completo incluyendo CPU y memoria, mientras que las VM solo virtualizan el sistema de archivos.",
        "option_b": "Los contenedores comparten el kernel del sistema operativo anfitrión y virtualizan solo el espacio de usuario, siendo más ligeros; las VM incluyen un SO completo por instancia.",
        "option_c": "Los contenedores requieren más recursos que las VM porque incluyen un hipervisor de Tipo 1 embebido en cada instancia.",
        "option_d": "No existe diferencia técnica; son términos distintos para la misma tecnología de aislamiento de procesos.",
        "correct_answer": "B",
        "explanation": "Las VM incluyen un SO completo (kernel + userspace) sobre el hipervisor, con mayor aislamiento pero más consumo de recursos. Los contenedores (Docker, LXC) comparten el kernel del host y solo aíslan el espacio de usuario mediante namespaces y cgroups. Son más ligeros, arrancan en segundos y son más portables, pero con menor aislamiento que las VM.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué es una snapshot en el contexto de una máquina virtual?",
        "option_a": "Una captura de pantalla automática del estado visual de la máquina virtual en un momento determinado.",
        "option_b": "Una copia del estado completo de la VM (disco, RAM, configuración) en un momento dado, que permite restaurar ese estado si algo falla.",
        "option_c": "Un archivo de configuración que define los recursos hardware asignados a la máquina virtual.",
        "option_d": "Un informe de rendimiento generado periódicamente por el hipervisor para monitorizar la VM.",
        "correct_answer": "B",
        "explanation": "Una snapshot (instantánea) captura el estado completo de una VM en un instante: el contenido del disco, el estado de la RAM y la configuración. Esto permite revertir la VM a ese punto exacto si una actualización, instalación o cambio de configuración causa problemas. Es una herramienta clave para testing y administración de sistemas.",
    },

    # ── ALMACENAMIENTO EN RED ──────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál de las siguientes representa una ventaja clave del almacenamiento en red (NAS/SAN)?",
        "option_a": "Ofrece una seguridad intrínseca superior, eliminando la necesidad de configuraciones de protección adicionales.",
        "option_b": "Mayor velocidad de acceso a los datos en comparación con almacenamiento local debido únicamente a la infraestructura de red.",
        "option_c": "Mayor accesibilidad desde cualquier equipo conectado a la misma red y facilita la centralización y gestión de los datos.",
        "option_d": "Elimina completamente la necesidad de copias de seguridad al replicar automáticamente todos los datos.",
        "correct_answer": "C",
        "explanation": "El almacenamiento en red (NAS o SAN) permite que múltiples equipos accedan a los mismos datos desde cualquier punto de la red, facilitando la colaboración y la administración centralizada. También simplifica las copias de seguridad al estar los datos en un único punto. No elimina la necesidad de seguridad adicional ni siempre supera en velocidad al almacenamiento local.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Cuál es la diferencia principal entre un NAS (Network Attached Storage) y un SAN (Storage Area Network)?",
        "option_a": "Un NAS usa conexiones inalámbricas WiFi, mientras que un SAN siempre usa fibra óptica.",
        "option_b": "Un NAS proporciona almacenamiento a nivel de archivo accesible por red (SMB, NFS), mientras que un SAN proporciona almacenamiento a nivel de bloque dedicado de alta velocidad.",
        "option_c": "Un NAS solo puede ser usado por un único equipo simultáneamente, mientras que un SAN permite acceso multiusuario.",
        "option_d": "Un SAN está diseñado para usuarios domésticos y un NAS para entornos empresariales de alta disponibilidad.",
        "correct_answer": "B",
        "explanation": "NAS presenta almacenamiento a nivel de archivo mediante protocolos de red como SMB (Windows) o NFS (Linux), siendo accesible directamente por múltiples clientes como si fuera una carpeta de red. SAN proporciona almacenamiento a nivel de bloque mediante Fibre Channel o iSCSI, que el servidor ve como un disco local de alta velocidad, siendo ideal para bases de datos y aplicaciones de alta demanda.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿Qué es RAID 5 y cuál es su principal ventaja frente a RAID 0?",
        "option_a": "RAID 5 duplica todos los datos en dos discos, ofreciendo mayor velocidad de escritura que RAID 0.",
        "option_b": "RAID 5 distribuye datos y paridad entre mínimo 3 discos, tolerando el fallo de un disco sin pérdida de datos; RAID 0 ofrece mayor rendimiento pero sin tolerancia a fallos.",
        "option_c": "RAID 5 es idéntico a RAID 0 pero requiere el doble de discos para operar correctamente.",
        "option_d": "RAID 5 solo se usa en entornos NAS domésticos, mientras que RAID 0 está diseñado para servidores empresariales.",
        "correct_answer": "B",
        "explanation": "RAID 0 (striping) reparte los datos entre discos para mayor rendimiento pero sin redundancia; si falla un disco se pierden todos los datos. RAID 5 (striping con paridad distribuida) necesita mínimo 3 discos, distribuye los datos y la información de paridad entre todos ellos, y puede reconstruir los datos si falla un único disco. Ofrece equilibrio entre rendimiento, capacidad y tolerancia a fallos.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Qué protocolo se usa principalmente para compartir carpetas de almacenamiento en red en entornos Windows?",
        "option_a": "FTP (File Transfer Protocol)",
        "option_b": "NFS (Network File System)",
        "option_c": "SMB/CIFS (Server Message Block)",
        "option_d": "iSCSI (Internet Small Computer Systems Interface)",
        "correct_answer": "C",
        "explanation": "SMB (Server Message Block), también conocido como CIFS, es el protocolo estándar de Microsoft para compartir archivos, impresoras y otros recursos en redes Windows. NFS es su equivalente en entornos Unix/Linux. FTP es un protocolo de transferencia de archivos y iSCSI es un protocolo de almacenamiento a nivel de bloque sobre redes IP.",
    },

    # ── CPD / BASTIDORES / RACKS ───────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "Al instalar equipos en un CPD, los bastidores o 'racks' son esenciales. ¿Qué característica es crucial en un bastidor para asegurar que los equipos no se sobrecalienten?",
        "option_a": "Su profundidad, que puede variar entre 600 mm y 1200 mm.",
        "option_b": "Que incluyan accesorios como paneles laterales y puertas con cerradura para mantener el calor contenido.",
        "option_c": "Contar con sistemas de ventilación adecuados como ventiladores de refrigeración, sistemas de enfriamiento por agua o aire acondicionado de precisión.",
        "option_d": "Que estén fabricados en acero galvanizado para maximizar la disipación de calor por convección.",
        "correct_answer": "C",
        "explanation": "La refrigeración es el factor crítico en el diseño de un rack para CPD. Los equipos de telecomunicaciones y servidores generan mucho calor, por lo que los bastidores deben integrar o permitir sistemas de ventilación como ventiladores, unidades de aire acondicionado de pasillo frío/caliente o incluso refrigeración líquida, para mantener los equipos dentro de su rango de temperatura operativo.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Qué unidad se usa para medir la altura de los equipos instalados en un rack de CPD?",
        "option_a": "Pulgadas (inch)",
        "option_b": "Unidades de rack (U), donde 1U = 44,45 mm de alto",
        "option_c": "Centímetros (cm), ya que los racks siguen el estándar métrico europeo",
        "option_d": "Slots, donde cada slot equivale a la altura de una tarjeta de expansión",
        "correct_answer": "B",
        "explanation": "La unidad rack (U) es el estándar de la industria para medir la altura de los equipos instalados en bastidores. 1U equivale a 44,45 mm (1,75 pulgadas). Un servidor 1U es muy delgado, mientras que un servidor 2U o 4U ocupa más espacio pero puede albergar más componentes. Los racks estándar tienen 42U de altura.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "Dentro de la estructura de un CPD, ¿cuál es la función principal del 'Área de red'?",
        "option_a": "Proporcionar un espacio climatizado para que los administradores monitoreen y gestionen los sistemas.",
        "option_b": "Albergar dispositivos como switches, routers y firewalls para garantizar la disponibilidad y seguridad de la red.",
        "option_c": "Alojar los sistemas de suministro eléctrico ininterrumpido como generadores y baterías UPS.",
        "option_d": "Gestionar el acceso físico de personal y el control de seguridad perimetral del centro de datos.",
        "correct_answer": "B",
        "explanation": "El Área de Red (o sala de comunicaciones) en un CPD alberga los equipos de networking: switches de core y de acceso, routers, firewalls, balanceadores de carga y paneles de parcheo. Su función es garantizar la conectividad, disponibilidad y seguridad de las comunicaciones entre servidores, sistemas de almacenamiento y la red exterior.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué es el concepto de 'pasillo frío / pasillo caliente' (cold aisle / hot aisle) en un CPD?",
        "option_a": "Una técnica de seguridad que separa físicamente los pasillos de acceso del personal de los pasillos de mantenimiento.",
        "option_b": "Una estrategia de organización de racks que alterna la orientación de los equipos para que las tomas de aire frío y las salidas de aire caliente queden en pasillos separados, mejorando la eficiencia de refrigeración.",
        "option_c": "Un sistema de detección de incendios que distingue entre zonas de alta y baja temperatura para una respuesta adecuada.",
        "option_d": "La separación entre el área de servidores de producción y el área de servidores de desarrollo para evitar interferencias térmicas.",
        "correct_answer": "B",
        "explanation": "El diseño pasillo frío/pasillo caliente organiza los racks en filas alternadas: los frentes de los servidores (que aspiran aire frío) dan al pasillo frío, y las partes traseras (que expulsan aire caliente) dan al pasillo caliente. Esto evita que el aire caliente se mezcle con el frío, mejorando la eficiencia energética del sistema de climatización del CPD.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿Qué indica el nivel Tier de un Centro de Procesamiento de Datos según el estándar Uptime Institute?",
        "option_a": "La capacidad de almacenamiento total expresada en petabytes.",
        "option_b": "El grado de redundancia e infraestructura del CPD, que determina su disponibilidad garantizada anualmente (de Tier I con 99,671% a Tier IV con 99,995%).",
        "option_c": "El número máximo de racks que puede alojar el centro de datos en su configuración estándar.",
        "option_d": "La certificación de seguridad física del centro de datos según normativas internacionales ISO.",
        "correct_answer": "B",
        "explanation": "El estándar Tier del Uptime Institute clasifica los CPD en cuatro niveles según su redundancia e infraestructura: Tier I (básico, 99,671% uptime, 28,8h parada/año), Tier II (componentes redundantes, 99,741%), Tier III (mantenimiento sin interrupciones, 99,982%) y Tier IV (totalmente tolerante a fallos, 99,995%, máximo 26,3 min parada/año).",
    },

    # ── ALTA DISPONIBILIDAD ────────────────────────────────────────────────────
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "Las arquitecturas de alta disponibilidad buscan garantizar la continuidad de los servicios TI. ¿Cuál de los siguientes aspectos es fundamental en su diseño?",
        "option_a": "Eliminar el control y la gestión remotos para evitar posibles fallos de conexión externa.",
        "option_b": "Priorizar la eficiencia energética por encima de la redundancia para reducir costes operativos.",
        "option_c": "La utilización de componentes redundantes en todo el sistema y técnicas de equilibrio de carga para distribuir el tráfico.",
        "option_d": "Concentrar todos los servicios críticos en un único servidor de alta gama para simplificar la administración.",
        "correct_answer": "C",
        "explanation": "La alta disponibilidad (HA) se basa en eliminar los puntos únicos de fallo (SPOF) mediante redundancia en todos los niveles: fuentes de alimentación, discos (RAID), servidores (clustering), conexiones de red (bonding/LACP) y centros de datos (geografía). El balanceo de carga distribuye el tráfico y permite que si un nodo falla, los demás absorban su trabajo sin interrupción del servicio.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué es un clúster de alta disponibilidad (HA cluster) en el contexto de servidores?",
        "option_a": "Un grupo de servidores que comparten el mismo procesador para multiplicar su potencia de cálculo.",
        "option_b": "Un conjunto de servidores configurados para que si uno falla, otro asuma automáticamente sus funciones sin interrupción del servicio.",
        "option_c": "Un conjunto de servidores idénticos que procesan peticiones simultáneamente para maximizar el rendimiento de cálculo.",
        "option_d": "Una red de servidores distribuidos geográficamente que se sincronizan cada 24 horas.",
        "correct_answer": "B",
        "explanation": "Un clúster HA agrupa dos o más servidores (nodos) donde uno activo procesa las peticiones y el/los otros están en modo standby monitorizando el estado del activo. Si el nodo activo falla, el proceso de failover transfiere automáticamente los servicios al nodo standby en segundos o minutos, garantizando la continuidad del servicio con mínima interrupción.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "hard",
        "text": "¿Qué diferencia existe entre RTO y RPO en el contexto de alta disponibilidad y recuperación ante desastres?",
        "option_a": "RTO es el ancho de banda de recuperación y RPO es el rendimiento del protocolo de copia de seguridad.",
        "option_b": "RTO (Recovery Time Objective) es el tiempo máximo tolerable para restaurar el servicio; RPO (Recovery Point Objective) es la pérdida máxima de datos tolerable en tiempo.",
        "option_c": "Ambos son equivalentes y miden el tiempo de inactividad aceptable; la diferencia es solo de nomenclatura según el proveedor.",
        "option_d": "RTO mide la disponibilidad anual en porcentaje y RPO mide el tiempo entre copias de seguridad planificadas.",
        "correct_answer": "B",
        "explanation": "RTO (Recovery Time Objective) define el tiempo máximo aceptable para restaurar un sistema tras un fallo (ej. 4 horas). RPO (Recovery Point Objective) define la cantidad máxima de datos que se puede perder medida en tiempo (ej. si RPO=1h, las copias de seguridad deben hacerse cada hora como mínimo). Son los dos parámetros clave para diseñar estrategias de DR y HA.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué función cumple un UPS (Sistema de Alimentación Ininterrumpida) en la infraestructura de un CPD?",
        "option_a": "Estabilizar la frecuencia de la señal de red WiFi para garantizar conexiones inalámbricas continuas.",
        "option_b": "Proporcionar alimentación eléctrica continua a los sistemas durante cortes o fluctuaciones de la red eléctrica, usando baterías como fuente de respaldo.",
        "option_c": "Gestionar la distribución de carga de trabajo entre los servidores del clúster para maximizar la eficiencia.",
        "option_d": "Monitorizar el consumo eléctrico de cada rack y ajustar automáticamente el voltaje para optimizar la eficiencia energética.",
        "correct_answer": "B",
        "explanation": "Un UPS (Uninterruptible Power Supply) protege los sistemas informáticos de cortes de suministro eléctrico, fluctuaciones de tensión y picos. Sus baterías internas proporcionan alimentación durante un corte para que los sistemas continúen operando o se apaguen de forma controlada. En CPDs se complementa con generadores diésel para cortes prolongados.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "easy",
        "text": "¿Qué significa que un sistema tiene una disponibilidad del '99,99%' (cuatro nueves)?",
        "option_a": "El sistema puede atender el 99,99% de las peticiones simultáneas sin degradación de rendimiento.",
        "option_b": "El sistema está operativo el 99,99% del tiempo anual, lo que equivale a un máximo de aproximadamente 52 minutos de parada al año.",
        "option_c": "El 99,99% de los datos almacenados están protegidos contra pérdida, y el 0,01% restante tiene un riesgo de pérdida aceptable.",
        "option_d": "El sistema puede recuperarse de cualquier fallo en menos de 99,99 segundos.",
        "correct_answer": "B",
        "explanation": "El 'número de nueves' es la métrica estándar para expresar la disponibilidad de un sistema. Una disponibilidad del 99,99% (cuatro nueves) permite un máximo de 52 minutos y 36 segundos de parada anual. Los sistemas de misión crítica persiguen los '5 nueves' (99,999%) que equivalen a solo 5,26 minutos de parada al año.",
    },
    {
        "subject": "Fundamentos de Hardware",
        "difficulty": "medium",
        "text": "¿Qué es el balanceo de carga (load balancing) y por qué es importante en arquitecturas de alta disponibilidad?",
        "option_a": "Es una técnica para equilibrar el consumo eléctrico entre los diferentes racks de un CPD.",
        "option_b": "Es un mecanismo que distribuye las peticiones entrantes entre múltiples servidores, evitando que uno se sature, mejorando el rendimiento y la disponibilidad del servicio.",
        "option_c": "Es un protocolo que sincroniza las copias de seguridad entre servidores de diferentes zonas geográficas.",
        "option_d": "Es una configuración de red que prioriza el tráfico crítico sobre el tráfico menos importante en momentos de alta demanda.",
        "correct_answer": "B",
        "explanation": "El load balancer (balanceador de carga) actúa como punto de entrada único que distribuye las peticiones entre un grupo de servidores backend según algoritmos como round-robin, least connections o IP hash. Aumenta la disponibilidad (si un servidor falla, el tráfico se redirige a los demás) y permite escalar horizontalmente añadiendo más servidores al pool.",
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = {q.text.strip().lower() for q in db.query(Question).all()}
        inserted, skipped = 0, 0

        for q in QUESTIONS:
            if q['text'].strip().lower() in existing:
                skipped += 1
                continue
            db.add(Question(
                subject        = q['subject'],
                difficulty     = q['difficulty'],
                text           = q['text'],
                option_a       = q['option_a'],
                option_b       = q['option_b'],
                option_c       = q['option_c'],
                option_d       = q['option_d'],
                correct_answer = q['correct_answer'],
                explanation    = q['explanation'],
                approved       = True,
            ))
            existing.add(q['text'].strip().lower())
            inserted += 1

        db.commit()
        print(f"\n✓ Insertadas: {inserted} preguntas nuevas")
        print(f"  Omitidas (duplicadas): {skipped}")
        print(f"  Total de preguntas añadidas a 'Fundamentos de Hardware': {inserted}\n")

    except Exception as e:
        db.rollback()
        print(f"\n✗ Error: {e}\n")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
