import json
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# DB Setup
from dotenv import load_dotenv
load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    # Fallback/Default for this specific environment based on .env view
    DATABASE_URL = "postgresql://tech4u_admin:tech4u_admin@localhost:5432/tech4u"

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def bulk_insert(exercises_list):
    from database import SkillLabExercise
    db = SessionLocal()
    try:
        count = 0
        for ex_data in exercises_list:
            exercise = SkillLabExercise(
                subject=ex_data['subject'],
                difficulty=ex_data['difficulty'],
                sentence_template=ex_data['sentence_template'],
                correct_answers=json.dumps(ex_data['correct_answers'], ensure_ascii=False),
                distractors=json.dumps(ex_data['distractors'], ensure_ascii=False),
                explanation=ex_data['explanation'],
                approved=True
            )
            db.add(exercise)
            count += 1
        db.commit()
        print(f"Successfully inserted {count} exercises.")
    except Exception as e:
        db.rollback()
        print(f"Error during insertion: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    # This will be populated with data generated by the AI
    data = [
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El sistema [BLANK] es la base de la mayoría de servidores web y sistemas embebidos por su robustez y seguridad.", "correct_answers": ["Linux"], "distractors": ["Windows", "macOS", "NetWare", "Solaris"], "explanation": "Linux es el núcleo de distribuciones como Ubuntu, Debian y CentOS."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "Un clúster de [BLANK] permite que varios servidores compartan la carga de trabajo para mejorar el rendimiento global.", "correct_answers": ["balanceo"], "distractors": ["datos", "red", "disco", "memoria"], "explanation": "Load Balancing Cluster."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La arquitectura de microservicios suele desplegarse en [BLANK] para facilitar la escalabilidad y el aislamiento.", "correct_answers": ["contenedores"], "distractors": ["máquinas virtuales", "servidores físicos", "mainframes", "nubes públicas"], "explanation": "Docker y Kubernetes son las tecnologías líderes."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "La latencia de red se mide normalmente en [BLANK] (ms).", "correct_answers": ["milisegundos"], "distractors": ["microsegundos", "segundos", "nanosegundos", "centisegundos"], "explanation": "Indica el tiempo que tarda un paquete en ir y volver."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El protocolo [BLANK] permite la transferencia de archivos de forma segura cifrando la sesión con SSH.", "correct_answers": ["SFTP"], "distractors": ["FTP", "TFTP", "HTTP", "SMB"], "explanation": "Secure File Transfer Protocol."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El [BLANK] es un parámetro de la BIOS/UEFI que permite al sistema operativo controlar el ahorro de energía del hardware.", "correct_answers": ["ACPI"], "distractors": ["PnP", "SATA", "PXE", "POST"], "explanation": "Advanced Configuration and Power Interface."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Un sistema [BLANK] es aquel que está diseñado para realizar una función específica dentro de un dispositivo más grande.", "correct_answers": ["embebido"], "distractors": ["abierto", "cerrado", "distribuido", "local"], "explanation": "También llamado sistema integrado o empotrado."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "La [BLANK] de datos es el proceso de crear una copia de seguridad para evitar la pérdida de información.", "correct_answers": ["copia"], "distractors": ["restauración", "migración", "sincronización", "duplicación"], "explanation": "Backup."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "En Windows Server, el rol [BLANK] permite desplegar sistemas operativos a través de la red de forma automatizada.", "correct_answers": ["WDS"], "distractors": ["WSUS", "IIS", "DHCP", "DNS"], "explanation": "Windows Deployment Services."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El [BLANK] es el software que permite gestionar y orquestar máquinas virtuales.", "correct_answers": ["hipervisor"], "distractors": ["kernel", "driver", "BIOS", "firmware"], "explanation": "Componente clave de la virtualización."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "Una red [BLANK] permite conectar oficinas geográficamente distantes a través de Internet de forma segura.", "correct_answers": ["VPN"], "distractors": ["LAN", "WLAN", "PAN", "MAN"], "explanation": "Virtual Private Network."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El [BLANK] de un procesador determina cuántos ciclos de reloj realiza por segundo.", "correct_answers": ["frecuencia"], "distractors": ["potencia", "voltaje", "consumo", "núcleo"], "explanation": "Se mide en Gigahercios (GHz)."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Para ver los archivos de una carpeta en la terminal de Windows se usa el comando [BLANK].", "correct_answers": ["dir"], "distractors": ["ls", "show", "list", "get"], "explanation": "Equivalente a ls en Linux."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El estándar [BLANK] permite que un ordenador arranque el sistema operativo directamente desde la red.", "correct_answers": ["PXE"], "distractors": ["BIOS", "UEFI", "SATA", "USB"], "explanation": "Preboot Execution Environment."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La [BLANK] por hardware es una característica de la CPU que debe activarse en la BIOS para mejorar el rendimiento de las máquinas virtuales.", "correct_answers": ["virtualización"], "distractors": ["aceleración", "emulación", "depuración", "sincronización"], "explanation": "Intel VT-x o AMD-V."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El panel de [BLANK] en Windows permite configurar aspectos del sistema como usuarios, impresoras y programas.", "correct_answers": ["Control"], "distractors": ["Tareas", "Herramientas", "Seguridad", "Inicio"], "explanation": "Interfaz clásica de configuración de Windows."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "Un servidor de [BLANK] traduce los nombres de dominio legibles para humanos en direcciones IP.", "correct_answers": ["DNS"], "distractors": ["DHCP", "FTP", "HTTP", "SMTP"], "explanation": "Domain Name System."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El protocolo [BLANK] se utiliza para la gestión y monitorización remota de dispositivos de red.", "correct_answers": ["SNMP"], "distractors": ["SMTP", "SSH", "ICMP", "UDP"], "explanation": "Simple Network Management Protocol."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "La papelera de [BLANK] en Windows permite recuperar archivos borrados accidentalmente.", "correct_answers": ["Reciclaje"], "distractors": ["Basura", "Eliminación", "Temporal", "Seguridad"], "explanation": "Almacén temporal de archivos borrados."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El [BLANK] remoto (RDP) es una herramienta de Microsoft que permite controlar un PC a distancia.", "correct_answers": ["Escritorio"], "distractors": ["Acceso", "Control", "Terminal", "Servicio"], "explanation": "Remote Desktop Protocol."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La [BLANK] redundante asegura que un servidor siga funcionando si falla una de sus fuentes de energía.", "correct_answers": ["alimentación"], "distractors": ["memoria", "red", "CPU", "refrigeración"], "explanation": "Suele implementarse con fuentes 'Hot-Swap'."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El comando [BLANK] en Windows se usa para verificar la conectividad con otro equipo de la red.", "correct_answers": ["ping"], "distractors": ["traceroute", "netstat", "route", "host"], "explanation": "Envía paquetes ICMP Eco Request."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "La [BLANK] de un disco duro es el tiempo que tarda el cabezal en situarse sobre el sector de datos deseado.", "correct_answers": ["latencia"], "distractors": ["velocidad", "capacidad", "transferencia", "frecuencia"], "explanation": "Es menor en los SSD al no tener partes mecánicas."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El sistema de archivos [BLANK] de Linux es el más común actualmente debido a su rendimiento y fiabilidad.", "correct_answers": ["ext4"], "distractors": ["ext3", "NTFS", "FAT32", "ZFS"], "explanation": "Fourth Extended File System."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Una [BLANK] de red permite conectar físicamente el ordenador a un cable Ethernet.", "correct_answers": ["tarjeta"], "distractors": ["placa", "memoria", "fuente", "unidad"], "explanation": "NIC (Network Interface Card)."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El comando [BLANK] de Linux permite cambiar el propietario de un archivo o directorio.", "correct_answers": ["chown"], "distractors": ["chmod", "chgrp", "touch", "rename"], "explanation": "Change Owner."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La [BLANK] de carga (Load Balancing) distribuye el tráfico entrante entre varios servidores para evitar saturaciones.", "correct_answers": ["balanceo"], "distractors": ["distribución", "asignación", "segmentación", "réplica"], "explanation": "Mejora la disponibilidad y escalabilidad."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El puerto [BLANK] es el estándar para la transmisión de video digital de alta definición entre el PC y el monitor.", "correct_answers": ["HDMI"], "distractors": ["VGA", "DVI", "USB", "SATA"], "explanation": "High-Definition Multimedia Interface."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "Un servidor [BLANK] asigna automáticamente direcciones IP a los dispositivos que se conectan a la red.", "correct_answers": ["DHCP"], "distractors": ["DNS", "WINS", "NAT", "Proxy"], "explanation": "Dynamic Host Configuration Protocol."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El [BLANK] es un registro de auditoría que guarda información sobre intentos de acceso fallidos al sistema.", "correct_answers": ["log"], "distractors": ["script", "buffer", "dump", "caché"], "explanation": "Esencial para la seguridad y el diagnóstico de problemas."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El [BLANK] de archivos en Windows permite navegar por las carpetas y gestionar documentos.", "correct_answers": ["Explorador"], "distractors": ["Navegador", "Buscador", "Gestor", "Administrador"], "explanation": "Windows Explorer."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "La memoria [BLANK] es una porción del disco duro que el sistema operativo usa como si fuera RAM cuando esta se agota.", "correct_answers": ["virtual"], "distractors": ["flash", "caché", "secundaria", "ROM"], "explanation": "Page file en Windows o Swap en Linux."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El estándar [BLANK] es un conjunto de especificaciones de interfaz para conectar la placa base a dispositivos de almacenamiento de alta velocidad.", "correct_answers": ["PCIe"], "distractors": ["SATA", "USB", "AGP", "IDE"], "explanation": "Peripheral Component Interconnect Express."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Un cable [BLANK] es el medio físico más común para conectar ordenadores en una red local cableada.", "correct_answers": ["Ethernet"], "distractors": ["Fibra", "USB", "HDMI", "SATA"], "explanation": "Normalmente con conectores RJ45."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El protocolo [BLANK] se utiliza para enviar correos electrónicos desde un cliente a un servidor.", "correct_answers": ["SMTP"], "distractors": ["POP3", "IMAP", "HTTP", "FTP"], "explanation": "Simple Mail Transfer Protocol."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "En Active Directory, un [BLANK] es un contenedor lógico que agrupa dominios que comparten un esquema común.", "correct_answers": ["bosque"], "distractors": ["árbol", "sitio", "unidad", "grupo"], "explanation": "Forest."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El software [BLANK] es aquel cuyo código fuente es accesible y puede ser modificado por cualquier persona.", "correct_answers": ["libre"], "distractors": ["gratuito", "privativo", "cerrado", "comercial"], "explanation": "Open Source."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "La [BLANK] es la temperatura máxima recomendada para el funcionamiento seguro de un procesador.", "correct_answers": ["T-junction"], "distractors": ["T-case", "Idle", "Peak", "Thermal"], "explanation": "Si se supera, el sistema suele apagarse por seguridad."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "Un servidor [BLANK] actúa como intermediario entre un cliente y el servidor de destino, filtrando el tráfico.", "correct_answers": ["proxy"], "distractors": ["firewall", "gateway", "bridge", "switch"], "explanation": "Puede usarse para mejorar la seguridad o el rendimiento (caché)."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El [BLANK] es la unidad mínima de información que puede procesar un ordenador.", "correct_answers": ["bit"], "distractors": ["byte", "kilobyte", "megabyte", "gigabyte"], "explanation": "Representa un 0 o un 1."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El comando [BLANK] de Linux muestra el uso de memoria RAM del sistema en tiempo real.", "correct_answers": ["free"], "distractors": ["top", "mem", "show", "status"], "explanation": "Muestra memoria total, usada, libre y caché."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La tecnología de memoria [BLANK] (ECC) permite detectar y corregir errores de un solo bit en los servidores.", "correct_answers": ["Error Correcting Code"], "distractors": ["Dual Channel", "Buffered", "Registered", "Non-Volatile"], "explanation": "Vital para sistemas que requieren alta fiabilidad."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Una [BLANK] es una copia exacta del estado de una máquina virtual en un momento determinado.", "correct_answers": ["instantánea"], "distractors": ["copia", "réplica", "imagen", "clonación"], "explanation": "Snapshot."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El protocolo [BLANK] permite sincronizar la hora de todos los equipos de una red con un servidor de hora preciso.", "correct_answers": ["NTP"], "distractors": ["HTTP", "SMTP", "SNMP", "TCP"], "explanation": "Network Time Protocol."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "El [BLANK] de memoria es una técnica que permite al procesador acceder a dos módulos de RAM simultáneamente para duplicar el ancho de banda.", "correct_answers": ["doble canal"], "distractors": ["overclocking", "caché", "virtualización", "paginación"], "explanation": "Dual Channel."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "El sistema operativo [BLANK] es el más común en dispositivos móviles como smartphones y tablets.", "correct_answers": ["Android"], "distractors": ["Windows", "Linux", "macOS", "NetWare"], "explanation": "Basado en el kernel de Linux."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El comando [BLANK] en Linux muestra el espacio libre en disco de todas las particiones montadas.", "correct_answers": ["df"], "distractors": ["du", "ls", "free", "space"], "explanation": "Disk Free."},
        {"subject": "Sistemas", "difficulty": "hard", "sentence_template": "La [BLANK] de un procesador indica cuántas tareas diferentes puede ejecutar de forma simultánea en hilos separados.", "correct_answers": ["multihilo"], "distractors": ["velocidad", "capacidad", "frecuencia", "potencia"], "explanation": "Multithreading."},
        {"subject": "Sistemas", "difficulty": "easy", "sentence_template": "Un [BLANK] es una red privada dentro de una organización que utiliza tecnologías de Internet.", "correct_answers": ["intranet"], "distractors": ["extranet", "internet", "VPN", "WAN"], "explanation": "Red interna corporativa."},
        {"subject": "Sistemas", "difficulty": "medium", "sentence_template": "El protocolo [BLANK] se utiliza para recuperar correos electrónicos de un servidor de forma que se descarguen al cliente local.", "correct_answers": ["POP3"], "distractors": ["IMAP", "SMTP", "HTTP", "FTP"], "explanation": "Post Office Protocol version 3."}
    ]
    if data:
        bulk_insert(data)
    else:
        print("No data provided in script.")
