"""
Seed: Ciberseguridad, Programación, Lenguaje de Marcas — 110 preguntas tipo test

Materias:
  - Ciberseguridad (40 preguntas): malware, pentesting, OWASP, herramientas, criptografía, etc.
  - Programación (40 preguntas): paradigmas, algoritmos, estructuras de datos, POO, Git, testing, APIs.
  - Lenguaje de Marcas (30 preguntas): HTML5, CSS, JavaScript, HTTP, REST, JSON, XML, accesibilidad.

Ejecutar desde la carpeta /backend con el venv activo:
  python seed_new_questions.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import SessionLocal, Question

QUESTIONS = [
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Cuál es la principal diferencia entre un virus informático y un gusano (worm)?',
        "option_a": 'El virus necesita un programa anfitrión para propagarse, mientras que el gusano se propaga de forma autónoma.',
        "option_b": 'Un gusano es más peligroso que un virus en todos los casos.',
        "option_c": 'El gusano solo afecta a sistemas Windows, mientras que el virus afecta a todos los SO.',
        "option_d": 'No hay diferencia; los términos son sinónimos en ciberseguridad.',
        "correct_answer": 'a',
        "explanation": 'Un virus es código malicioso que debe incorporarse a un programa legítimo para ejecutarse y replicarse. Un gusano es malware autónomo que se propaga por la red sin necesidad de un anfitrión, consumiendo recursos y ralentizando sistemas.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué tipo de malware encripta los archivos de una víctima y exige un pago para restaurarlos?',
        "option_a": 'Spyware',
        "option_b": 'Rootkit',
        "option_c": 'Ransomware',
        "option_d": 'Adware',
        "correct_answer": 'c',
        "explanation": 'El ransomware es malware que cifra los datos del usuario haciendo que no sean accesibles, y luego pide un rescate (ransom) para proporcionar la clave de descifrado. Ataques recientes contra empresas como Colonial Pipeline han demostrado el impacto crítico de esta amenaza.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": 'Un rootkit es un tipo de malware que principalmente se caracteriza por:',
        "option_a": 'Mostrar anuncios publicitarios invasivos en el navegador.',
        "option_b": 'Acceder y recopilar datos sensibles del usuario sin consentimiento.',
        "option_c": 'Obtener acceso de nivel de raíz (root/administrador) y ocultarse profundamente en el sistema.',
        "option_d": 'Destruir el bootloader del dispositivo permanentemente.',
        "correct_answer": 'c',
        "explanation": 'Un rootkit es malware sofisticado que obtiene privilegios de root/administrador y se oculta del sistema operativo y las herramientas de seguridad, permitiendo al atacante mantener acceso persistente y control total del equipo.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Cuál de estos tipos de malware tiene como objetivo recopilar datos sensibles del usuario (contraseñas, información bancaria)?',
        "option_a": 'Spyware',
        "option_b": 'Gusano',
        "option_c": 'Botnet',
        "option_d": 'Troyano',
        "correct_answer": 'a',
        "explanation": 'El spyware es malware que monitorea las actividades del usuario, recopilando información personal como pulsaciones de teclado (keylogging), contraseñas, datos bancarios y navegación web, transmitiéndola a servidores de comando y control del atacante.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es una botnet y cómo se utiliza típicamente en ataques cibernéticos?',
        "option_a": 'Una red de robots que limpian automáticamente los virus de los equipos infectados.',
        "option_b": 'Una red de dispositivos comprometidos controlados remotamente para lanzar ataques DDoS, enviar spam o minar criptomonedas.',
        "option_c": 'Un firewall avanzado que protege contra múltiples atacantes simultáneamente.',
        "option_d": 'Un software que detecta y elimina troyanos del sistema operativo.',
        "correct_answer": 'b',
        "explanation": 'Una botnet es un conjunto de dispositivos (ordenadores, routers, IoT) infectados por malware y controlados por un atacante a través de servidores C&C. Se utiliza para ataques DDoS masivos, distribución de malware, fraude, robo de datos y minería de criptomonedas.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es la primera fase de un test de penetración (pentesting)?',
        "option_a": 'Explotación de vulnerabilidades encontradas.',
        "option_b": 'Reconocimiento e información de la empresa objetivo.',
        "option_c": 'Generación del informe final con los resultados.',
        "option_d": 'Post-explotación y mantenimiento de acceso.',
        "correct_answer": 'b',
        "explanation": 'La fase de reconocimiento (reconnaissance) es la primera del pentesting, donde el tester recopila información sobre el objetivo: dominio, empleados, tecnologías usadas, registros DNS, redes, mediante técnicas de OSINT (inteligencia de fuente abierta) sin conexiones directas al sistema.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué actividades se llevan a cabo en la fase de escaneo de un pentesting?',
        "option_a": 'Solo observar el tráfico de red sin hacer conexiones activas.',
        "option_b": 'Identificar puertos abiertos, servicios activos y posibles vulnerabilidades mediante herramientas como Nmap y Nessus.',
        "option_c": 'Comprometer directamente los sistemas y acceder a datos sensibles.',
        "option_d": 'Realizar ingeniería social y phishing contra empleados.',
        "correct_answer": 'b',
        "explanation": 'En la fase de escaneo se emplean herramientas activas como Nmap (escaneo de puertos), Nessus, OpenVAS y GVM para identificar servicios, versiones de software y vulnerabilidades conocidas, sin explotar aún las vulnerabilidades.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": 'Durante la fase de post-explotación en un pentesting, ¿cuál es el objetivo principal del tester?',
        "option_a": 'Destruir todos los datos del sistema objetivo para demostrar su vulnerabilidad.',
        "option_b": 'Mantener el acceso, escalar privilegios, pivotar a otros sistemas y recopilar información sensible.',
        "option_c": 'Desconectarse inmediatamente después de explotar una vulnerabilidad.',
        "option_d": 'Instalar defensa adicional de forma permanente en los sistemas.',
        "correct_answer": 'b',
        "explanation": 'La post-explotación es la fase donde el tester mantiene el acceso adquirido, intenta escalar privilegios (obtener acceso root), pivota lateralmente a otros sistemas de la red, recopila datos sensibles y demuestra el alcance completo de la brecha para el informe final.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Qué es la inyección SQL (SQL Injection) y por qué es crítica según OWASP?',
        "option_a": 'Un error de programación que causa que una base de datos funcione más lentamente.',
        "option_b": 'Un ataque donde se inyectan comandos SQL maliciosos en campos de entrada para ejecutar consultas no autorizadas.',
        "option_c": 'Un protocolo de seguridad para cifrar las bases de datos.',
        "option_d": 'Una herramienta de administración de bases de datos.',
        "correct_answer": 'b',
        "explanation": 'SQL Injection ocurre cuando una aplicación web incluye directamente entrada de usuario en consultas SQL sin sanitizar. Un atacante puede inyectar código SQL para modificar consultas, extraer datos, modificar o eliminar registros, o bypasear autenticación. Es el #3 en OWASP Top 10 2021.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cómo puede un atacante explotar Cross-Site Scripting (XSS) para comprometer a los usuarios de una aplicación web?',
        "option_a": 'Inyectando código JavaScript malicioso en páginas web que se ejecuta en el navegador de las víctimas.',
        "option_b": 'Accediendo directamente a la base de datos del servidor.',
        "option_c": 'Modificando el código fuente del servidor web.',
        "option_d": 'Interrumpiendo la conexión de red entre cliente y servidor.',
        "correct_answer": 'a',
        "explanation": 'XSS permite a atacantes inyectar código JavaScript en páginas web que se ejecuta en navegadores de usuarios legítimos, permitiendo robar cookies de sesión, credenciales, redirigir a sitios maliciosos o realizar acciones en nombre del usuario. Es el #7 en OWASP Top 10 2021.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es Cross-Site Request Forgery (CSRF) y cómo protegerse contra este ataque?',
        "option_a": 'Un ataque donde se fuerza al navegador de un usuario a realizar peticiones sin su consentimiento mediante tokens CSRF.',
        "option_b": 'Un ataque que solo afecta a navegadores antiguos como Internet Explorer 6.',
        "option_c": 'Una técnica de encriptación para proteger datos en tránsito.',
        "option_d": 'Un virus que infecta archivos de configuración del navegador.',
        "correct_answer": 'a',
        "explanation": 'CSRF ocurre cuando un atacante engaña a un usuario autenticado para realizar acciones no deseadas (transferencias, cambios de contraseña) desde otro sitio web. Se previene usando tokens CSRF únicos por sesión y verificando el origen de las peticiones (Same-Site cookies).',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Qué es una vulnerabilidad de Identificación y Autenticación Rota (Broken Authentication) según OWASP?',
        "option_a": 'Cuando el servidor no puede verificar identidades de usuarios de forma segura, permitiendo acceso no autorizado.',
        "option_b": 'Cuando los usuarios olvidan sus contraseñas regularmente.',
        "option_c": 'Cuando la red no tiene suficiente ancho de banda.',
        "option_d": 'Cuando el servidor debe reiniciarse después de cambiar contraseñas.',
        "correct_answer": 'a',
        "explanation": 'Broken Authentication incluye fallos como sesiones mal gestionadas (predecibles, no expiración), credenciales débiles, falta de multi-factor authentication (MFA), password reset inseguro o reutilización de sesiones. Permite a atacantes comprometer contraseñas, tokens o sesiones de usuario.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Para qué sirve Burp Suite y cuál es su rol principal en pruebas de seguridad web?',
        "option_a": 'Es un navegador avanzado que protege contra malware mientras se navega por internet.',
        "option_b": 'Es una suite de pruebas de seguridad web que intercepta y modifica peticiones HTTP/HTTPS para identificar vulnerabilidades.',
        "option_c": 'Es un servidor VPN que cifra todo el tráfico de internet.',
        "option_d": 'Es una herramienta de gestión de bases de datos SQL.',
        "correct_answer": 'b',
        "explanation": 'Burp Suite es un conjunto integrado de herramientas para testing de seguridad web que incluye proxy para interceptar requests, scanner automático de vulnerabilidades, herramientas de fuzzing y análisis de respuestas. Es estándar en la industria para penetesting y SDLC seguro.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué herramienta de code exploitation se utiliza comúnmente para desarrollar exploits y exfiltración de datos en pentesting?',
        "option_a": 'Metasploit Framework',
        "option_b": 'Wireshark',
        "option_c": 'John the Ripper',
        "option_d": 'Aircrack-ng',
        "correct_answer": 'a',
        "explanation": 'Metasploit es un framework opensource de penetración que contiene miles de exploits, payloads y herramientas para desarrollo de exploits, fuzzing, ingeniería social, post-explotación y obfuscación de código. msfconsole es la consola principal donde se ejecutan los módulos.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Para qué se utiliza la herramienta Wireshark en análisis de seguridad?',
        "option_a": 'Para interceptar y analizar tráfico de red a nivel de paquete, identificando comunicaciones sospechosas.',
        "option_b": 'Para romper contraseñas mediante ataques de fuerza bruta.',
        "option_c": 'Para escanear redes inalámbricas y crackear contraseñas WiFi.',
        "option_d": 'Para compilar código malicioso y empaquetarlo.',
        "correct_answer": 'a',
        "explanation": 'Wireshark es un analizador de protocolos que captura paquetes de red en tiempo real, permitiendo al tester examinar el contenido de las comunicaciones, identificar datos sensibles sin cifrar, anomalías de tráfico y protocolos inseguros como HTTP o Telnet.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito principal de Aircrack-ng en auditorías de seguridad wireless?',
        "option_a": 'Escalar privilegios en sistemas operativos Linux.',
        "option_b": 'Monitorear tráfico HTTPS cifrado sin necesidad de certificados.',
        "option_c": 'Auditar redes inalámbricas WiFi, capturar handshakes y crackear contraseñas WEP/WPA.',
        "option_d": 'Escanear puertos abiertos en servidores remotos.',
        "correct_answer": 'c',
        "explanation": 'Aircrack-ng es una suite de herramientas para auditoría de redes inalámbricas que permite capturar tráfico WiFi en modo monitor, recolectar handshakes WPA/WPA2 (4-way handshake) y realizar ataques de diccionario o fuerza bruta para recuperar contraseñas WiFi.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Para qué tipo de ataque se utiliza principalmente la herramienta John the Ripper?',
        "option_a": 'Para explotar vulnerabilidades de buffer overflow en aplicaciones.',
        "option_b": 'Para crackear hashes de contraseñas mediante ataques de diccionario, fuerza bruta y reglas personalizadas.',
        "option_c": 'Para sniffear contraseñas de redes inalámbricas.',
        "option_d": 'Para ejecutar exploit code en sistemas remotos.',
        "correct_answer": 'b',
        "explanation": 'John the Ripper es una herramienta de cracking de contraseñas optimizada que puede romper hashes (MD5, SHA-1, bcrypt, etc.) usando diccionarios, fuerza bruta y reglas que generan variaciones de palabras. Soporta múltiples formatos de hashes de diferentes aplicaciones.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Cuál es la principal ventaja de Hashcat frente a John the Ripper en cracking de contraseñas?',
        "option_a": 'Hashcat solo funciona con contraseñas de Windows.',
        "option_b": 'Hashcat utiliza aceleración GPU para paralelizar cálculos hash, siendo significativamente más rápido.',
        "option_c": 'John the Ripper solo puede crackear hashes MD5.',
        "option_d": 'Hashcat no requiere diccionarios predefinidos.',
        "correct_answer": 'b',
        "explanation": 'Hashcat aprovecha la potencia de GPUs (NVIDIA CUDA, AMD HIP, Intel OpenCL) para paralelizar millones de cálculos hash por segundo, siendo cientos de veces más rápido que John the Ripper que usa CPU. Soporta múltiples modos de ataque y algoritmos hash.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Cuál es la principal ventaja de HTTPS sobre HTTP?',
        "option_a": 'HTTPS es más rápido que HTTP.',
        "option_b": 'HTTPS cifra la comunicación entre cliente y servidor, protegiendo datos contra interception.',
        "option_c": 'HTTPS permite más conexiones simultáneas.',
        "option_d": 'HTTPS no requiere certificados SSL/TLS.',
        "correct_answer": 'b',
        "explanation": 'HTTPS utiliza TLS/SSL para cifrar toda la comunicación HTTP entre navegador y servidor, protegiendo contra eavesdropping y man-in-the-middle attacks. Los certificados digitales autentican la identidad del servidor, verificados por autoridades certificadoras (CA).',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué mejoras proporciona TLS 1.3 respecto a versiones anteriores?',
        "option_a": 'Elimina completamente la necesidad de certificados digitales.',
        "option_b": 'Reduce el overhead de handshake, usa algoritmos más seguros, y elimina protocolos criptográficos débiles como RC4.',
        "option_c": 'Permite cifrado de datos en HTTP sin HTTPS.',
        "option_d": 'Aumenta la compatibilidad con navegadores antiguos.',
        "correct_answer": 'b',
        "explanation": 'TLS 1.3 simplifica el handshake a 1 RTT (reduciendo latencia), elimina algoritmos débiles (DES, RC4), requiere Perfect Forward Secrecy (PFS), y usa solo AEAD ciphers (ChaCha20-Poly1305, AES-GCM). Es el estándar moderno de facto desde 2018.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Para qué se utiliza SSH y por qué es superior a Telnet?',
        "option_a": 'SSH es un protocolo más antiguo que Telnet.',
        "option_b": 'SSH proporciona acceso remoto seguro con cifrado de credenciales y comunicación, mientras que Telnet transmite todo en texto plano.',
        "option_c": 'Telnet es más rápido que SSH.',
        "option_d": 'SSH solo funciona en redes locales.',
        "correct_answer": 'b',
        "explanation": 'SSH cifra toda la sesión remota usando criptografía asimétrica y simétrica, protegiendo credenciales y datos contra interception. Soporta autenticación basada en claves (más segura que contraseñas) y permite tunneling de otros protocolos de forma segura.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es la principal diferencia entre criptografía simétrica y asimétrica?',
        "option_a": 'La criptografía simétrica es siempre más segura que la asimétrica.',
        "option_b": 'La simétrica usa una clave compartida para cifrar/descifrar, la asimétrica usa par de claves (pública/privada).',
        "option_c": 'La asimétrica es más rápida que la simétrica.',
        "option_d": 'Solo existe la criptografía simétrica en la práctica moderna.',
        "correct_answer": 'b',
        "explanation": 'Criptografía simétrica (AES, 3DES) usa una misma clave para cifrar y descifrar, siendo rápida pero requiriendo intercambio seguro de claves. Asimétrica (RSA, ECC) usa clave pública para cifrar y privada para descifrar, resolviendo el problema de intercambio pero siendo más lenta.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Por qué se considera que MD5 y SHA-1 no son seguros para aplicaciones modernas?',
        "option_a": 'Porque son demasiado lentos en computadoras modernas.',
        "option_b": 'Porque se han encontrado colisiones criptográficas prácticas, permitiendo generar inputs distintos con el mismo hash.',
        "option_c": 'Porque requieren más memoria que SHA-256.',
        "option_d": 'Porque no son de código abierto.',
        "correct_answer": 'b',
        "explanation": 'MD5 (colisiones publicadas en 2004) y SHA-1 (ataques prácticos SHAttered en 2017) son criptográficamente rotos. Los atacantes pueden crear dos inputs diferentes con el mismo hash, permitiendo falsificar certificados, firmas digitales y verificaciones de integridad. SHA-256 sigue siendo seguro.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Cuáles son las ventajas de bcrypt y scrypt respecto a almacenar hashes SHA-256 de contraseñas?',
        "option_a": 'Son más rápidos de calcular que SHA-256.',
        "option_b": 'Incluyen factor de estiramiento (salting) y ralentización intencional (key derivation) contra ataques de fuerza bruta.',
        "option_c": 'No requieren almacenamiento de salt separado.',
        "option_d": 'Son algoritmos de encriptación, no de hashing.',
        "correct_answer": 'b',
        "explanation": 'bcrypt (Blowfish + salt) y scrypt son funciones de derivación de claves que intentan ser computacionalmente costosas, haciéndolas lentas incluso para atacantes con GPUs. Incluyen salt aleatorio por defecto y parámetro de costo configurable para aumentar la resistencia conforme avanza la tecnología.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre un firewall stateless y uno stateful?',
        "option_a": 'Un firewall stateless examina cada paquete sin contexto, mientras que uno stateful mantiene registro del estado de conexiones.',
        "option_b": 'Los firewalls stateful son obsoletos en redes modernas.',
        "option_c": 'Un firewall stateless es más seguro que uno stateful.',
        "option_d": 'No existe diferencia; son términos sinónimos.',
        "correct_answer": 'a',
        "explanation": 'Un firewall stateless examina cada paquete independientemente contra reglas (ej: permitir puerto 80). Uno stateful mantiene tabla de conexiones activas y permite/bloquea respuestas basándose en si corresponden a conexiones establecidas, siendo más inteligente contra ataques.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Cuál es el propósito principal de una DMZ (Zona Desmilitarizada) en arquitectura de red?',
        "option_a": 'Permitir acceso público sin restricciones a todos los servidores.',
        "option_b": 'Aislar servidores accesibles desde internet (web, mail, DNS) de la red interna privada.',
        "option_c": 'Acelerar la velocidad de internet.',
        "option_d": 'Eliminar la necesidad de firewalls.',
        "correct_answer": 'b',
        "explanation": 'Una DMZ es una zona de red intermedia donde se colocan servidores expuestos a internet. Un firewall controla tráfico entre internet y DMZ, y otro entre DMZ y red interna, limitando daños si un servidor en DMZ es comprometido.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es la principal diferencia entre un IDS (Intrusion Detection System) y un IPS (Intrusion Prevention System)?',
        "option_a": 'Un IDS previene intrusiones activamente, un IPS solo detecta y alerta.',
        "option_b": 'Un IDS detecta y alerta sobre intrusiones, un IPS detecta y bloquea automáticamente el tráfico malicioso.',
        "option_c": 'Un IPS es una versión antigua de IDS.',
        "option_d": 'Solo existe IDS en redes modernas.',
        "correct_answer": 'b',
        "explanation": 'IDS (pasivo) monitorea el tráfico y genera alertas cuando detecta patrones de ataque (firmas o anomalías). IPS (activo) va más allá bloqueando/resetando conexiones maliciosas automáticamente. Ambos usan bases de datos de firmas de malware y técnicas de detección de anomalías.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es un CVE (Common Vulnerabilities and Exposures) y para qué sirve?',
        "option_a": 'Es un estándar para clasificar sistemas operativos.',
        "option_b": 'Es un identificador único para vulnerabilidades de seguridad públicamente conocidas, permitiendo tracking y gestión.',
        "option_c": 'Es un protocolo de cifrado de datos.',
        "option_d": 'Es un tipo de malware que solo afecta a sistemas antiguos.',
        "correct_answer": 'b',
        "explanation": 'CVE (ej: CVE-2021-44228 Log4j) es un identificador único mantenido por MITRE que permite referirse de forma estándar a vulnerabilidades. Cada CVE tiene descripción, afectados, impacto y referencias a patches, facilitando la gestión de vulnerabilidades en organizaciones.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué representa el CVSS score (Common Vulnerability Scoring System) y cómo se interpreta?',
        "option_a": 'Un número entre 0-100 que indica el nivel de severidad de una vulnerabilidad.',
        "option_b": 'Un porcentaje de dispositivos afectados por una vulnerabilidad.',
        "option_c": 'Una medida de velocidad de explotación en la red.',
        "option_d": 'Un precio estimado para corregir una vulnerabilidad.',
        "correct_answer": 'a',
        "explanation": 'CVSS es una puntuación de 0-10 (0-100 en v3.1) que califica severidad considerando: base (accesibilidad, complejidad, privilegios), temporal (disponibilidad de parches), ambiental. Puntuación 9+ es crítica y requiere mitigación inmediata. Es estándar en la industria para priorizar parches.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Qué es un ataque de día cero (zero-day) y por qué es especialmente peligroso?',
        "option_a": 'Un ataque que ocurre exactamente a las 00:00 horas.',
        "option_b": 'Un ataque que explota una vulnerabilidad desconocida sin parche disponible, dando cero días para defenderse.',
        "option_c": 'Un ataque que es bloqueado por antivirus en cero segundos.',
        "option_d": 'Un ataque que solo afecta servidores nuevos.',
        "correct_answer": 'b',
        "explanation": 'Un zero-day explota vulnerabilidades desconocidas para el vendedor/comunidad, por lo que no hay parche disponible. Los atacantes mantienen el conocimiento en secreto para maximizar daño. Es altamente valioso y típicamente usado en APTs contra objetivos de alto valor.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Qué es el phishing y cuál es su objetivo principal?',
        "option_a": 'Un tipo de malware que destruye datos.',
        "option_b": 'Un ataque de ingeniería social que engaña a usuarios para revelar credenciales o información sensible mediante emails falsos.',
        "option_c": 'Un protocolo de seguridad para redes inalámbricas.',
        "option_d": 'Un software de análisis de redes.',
        "correct_answer": 'b',
        "explanation": 'Phishing es un ataque de ingeniería social donde atacantes envían emails o mensajes falsificando instituciones legítimas (bancos, PayPal, redes sociales), solicitando al usuario que haga clic en enlaces falsos o ingrese credenciales en formularios fraudulentos.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es la principal característica de un ataque de spear phishing respecto al phishing común?',
        "option_a": 'El spear phishing afecta a una cantidad mayor de víctimas.',
        "option_b": 'El spear phishing está dirigido a individuos o grupos específicos usando información personalizada sobre ellos.',
        "option_c": 'El spear phishing usa técnicas de criptografía avanzada.',
        "option_d": 'El spear phishing es un tipo de malware, no de ingeniería social.',
        "correct_answer": 'b',
        "explanation": 'Spear phishing es una variante dirigida y personalizada de phishing donde el atacante investiga a víctimas específicas (empleados ejecutivos, profesionales) usando OSINT para personalizando el ataque con detalles reales, aumentando significativamente la probabilidad de éxito.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es el pretexting y cómo se diferencia del phishing?',
        "option_a": 'Pretexting es un sinónimo de phishing.',
        "option_b": 'Pretexting es un ataque donde el atacante crea un escenario falso para obtener información mediante interacción directa (llamadas, conversaciones).',
        "option_c": 'Pretexting es una técnica de encriptación.',
        "option_d": 'Pretexting es un software de seguridad.',
        "correct_answer": 'b',
        "explanation": "Pretexting es ingeniería social que implica crear un contexto falso y convincente para manipular personas a revelar información. Ej: atacante se hace pasar por técnico de IT pidiendo contraseña para 'mantenimiento'. Es más directo que phishing por email.",
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito de fail2ban en la seguridad de un servidor Linux?',
        "option_a": 'Comprime archivos de log para ahorrar espacio.',
        "option_b": 'Monitorea intentos fallidos de autenticación y bloquea dinámicamente IPs con múltiples fallos.',
        "option_c": 'Acelera la velocidad de procesamiento del servidor.',
        "option_d": 'Elimina virus de forma automática.',
        "correct_answer": 'b',
        "explanation": 'fail2ban es un herramienta que monitorea logs (SSH, Apache, etc.), detecta patrones de ataques (múltiples intentos fallidos) y bloquea dinámicamente IPs atacantes a través del firewall. Previene ataques de fuerza bruta contra SSH y servicios web.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Cuál es el rol de una Autoridad Certificadora (CA) en la infraestructura PKI?',
        "option_a": 'Generar pares de claves criptográficas para todos los usuarios.',
        "option_b": 'Emitir y firmar digitalmente certificados X.509 que vinculan claves públicas con identidades verificadas.',
        "option_c": 'Almacenar todas las claves privadas de los usuarios en servidores centrales.',
        "option_d": 'Cifrar emails antes de enviarlos.',
        "correct_answer": 'b',
        "explanation": 'Una CA (Certificate Authority) valida la identidad del solicitante (verificación de documento), genera certificados X.509 firmados digitalmente que asocian la clave pública con esa identidad. CAs raíz confiables están pre-instaladas en navegadores y SO. Las CAs intermedias crean cadenas de confianza.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Cuál es la diferencia principal entre programación imperativa y declarativa?',
        "option_a": 'La imperativa es más rápida que la declarativa.',
        "option_b": 'La imperativa describe cómo hacer algo (pasos), la declarativa describe qué resultado quieres sin especificar pasos.',
        "option_c": 'Solo existe la programación imperativa en lenguajes modernos.',
        "option_d": 'La declarativa es más antigua que la imperativa.',
        "correct_answer": 'b',
        "explanation": "Imperativa: 'Calcula suma iterando array' (Python for loop). Declarativa: 'Dame la suma de array' (SQL SELECT SUM(), o funcional map/reduce). SQL, HTML y lenguajes funcionales son declarativos; Java, C, Python son imperativos.",
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuáles son las características principales de la programación funcional?',
        "option_a": 'Uso de funciones como ciudadanos de primera clase, evitar cambios de estado, usar funciones puras.',
        "option_b": 'Solo se puede usar en lenguajes como Lisp y Scheme.',
        "option_c": 'La programación funcional es siempre más rápida que la imperativa.',
        "option_d": 'No se pueden usar variables en programación funcional.',
        "correct_answer": 'a',
        "explanation": 'Programación funcional enfatiza funciones puras (sin efectos laterales), inmutabilidad de datos, composición de funciones y orden superior (funciones como parámetros). Lenguajes: Haskell, Lisp, Clojure. Python, JavaScript también soportan elementos funcionales.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es el principio fundamental de la Programación Orientada a Objetos (POO)?',
        "option_a": 'Organizar código en clases y objetos que encapsulan datos y comportamiento.',
        "option_b": 'Minimizar el uso de variables.',
        "option_c": 'Prohibir el uso de funciones.',
        "option_d": 'Separar completamente datos de lógica.',
        "correct_answer": 'a',
        "explanation": 'POO agrupa datos (atributos) y métodos (funciones) relacionados en clases, creando objetos reutilizables. Principios clave: encapsulación, herencia, polimorfismo. Lenguajes: Java, Python, C++, C#.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la complejidad temporal de un algoritmo que itera dos bucles anidados sobre un array de n elementos?',
        "option_a": 'O(1) - tiempo constante',
        "option_b": 'O(n) - tiempo lineal',
        "option_c": 'O(n²) - tiempo cuadrático',
        "option_d": 'O(n!) - tiempo factorial',
        "correct_answer": 'c',
        "explanation": 'Dos bucles anidados: for(i=0; i<n; i++) for(j=0; j<n; j++) genera n × n = n² iteraciones. La complejidad es O(n²). Búsqueda lineal es O(n), binary search O(log n), factorial O(n!).',
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Por qué un algoritmo O(n log n) es preferible a uno O(n²) para arrays grandes?',
        "option_a": 'Porque O(n log n) usa menos memoria.',
        "option_b": 'Porque O(n log n) crece más lentamente. Para n=1.000.000, O(n²) requiere 10¹² ops vs O(n log n) con ~20M ops.',
        "option_c": 'Porque O(n log n) es siempre el óptimo teórico.',
        "option_d": 'Porque O(n log n) es más fácil de entender.',
        "correct_answer": 'b',
        "explanation": 'La notación O describe cómo crece el tiempo con tamaño de entrada. O(n log n) crece mucho más lentamente que O(n²). Para n=1M: n²=10¹², n log n ≈ 20M. Merge sort y quicksort average son O(n log n); bubble sort es O(n²).',
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Cuál es la diferencia entre una pila (stack) y una cola (queue)?',
        "option_a": 'Una pila es bidireccional, una cola unidireccional.',
        "option_b": 'Una pila usa LIFO (Last In First Out), una cola FIFO (First In First Out).',
        "option_c": 'Una pila almacena números, una cola almacena texto.',
        "option_d": 'No hay diferencia; son sinónimos.',
        "correct_answer": 'b',
        "explanation": 'Pila LIFO: último elemento añadido es el primero removido (push/pop). Cola FIFO: primer elemento añadido es el primero removido (enqueue/dequeue). Pila: undo/redo. Cola: procesar peticiones en orden.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la principal ventaja de una lista enlazada sobre un array?',
        "option_a": 'Una lista enlazada accede a elementos más rápido.',
        "option_b": 'Una lista enlazada permite inserciones/eliminaciones O(1) sin reorganizar memoria.',
        "option_c": 'Una lista enlazada usa menos memoria que un array.',
        "option_d": 'Una lista enlazada soporta búsqueda binaria.',
        "correct_answer": 'b',
        "explanation": 'Array: inserción/eliminación O(n) porque requiere desplazar elementos. Lista enlazada: inserción/eliminación O(1) si tienes referencia al nodo. Desventaja: acceso es O(n) vs O(1) en arrays. Trade-off: flexibilidad vs acceso rápido.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la función principal de una tabla hash (hash table)?',
        "option_a": 'Almacenar elementos ordenados para búsqueda binaria.',
        "option_b": 'Almacenar pares clave-valor permitiendo búsqueda, inserción y eliminación en O(1) promedio.',
        "option_c": 'Cifrar datos usando hash criptográfico.',
        "option_d": 'Comprimir datos en memoria.',
        "correct_answer": 'b',
        "explanation": 'Una tabla hash mapea claves a valores usando una función hash que calcula índices de array. Búsqueda/inserción/eliminación son O(1) promedio (O(n) worst-case con colisiones). Colisiones se resuelven por encadenamiento o direccionamiento abierto.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Qué es un árbol binario de búsqueda (BST) y cuál es su ventaja principal?',
        "option_a": 'Un árbol donde cada nodo tiene exactamente 2 hijos.',
        "option_b": 'Un árbol donde valores menores están a la izquierda, mayores a la derecha, permitiendo búsqueda O(log n).',
        "option_c": 'Un árbol que siempre está completamente balanceado.',
        "option_d": 'Un árbol que solo almacena números pares.',
        "correct_answer": 'b',
        "explanation": 'BST mantiene invariante: izquierda < nodo < derecha. Búsqueda es O(log n) si está balanceado (AVL, Red-Black tree). Desequilibrado puede degenerar a O(n). Utiles para conjuntos ordenados y búsqueda de rangos.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es una list comprehension en Python y cuál es su ventaja?',
        "option_a": 'Una forma alternativa de escribir bucles for más compacta y legible.',
        "option_b": 'Una lista que ocupa menos memoria.',
        "option_c": 'Una lista de todas las variables comprendidas en un programa.',
        "option_d": 'Un protocolo de comunicación entre aplicaciones.',
        "correct_answer": 'a',
        "explanation": 'List comprehension: [x*2 for x in range(10)] es equivalente pero más legible que: result=[]; [result.append(x*2) for x in range(10)]. Soporta condicionales: [x for x in range(10) if x%2==0]. Análoga: dict comprehension, set comprehension.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es un generador en Python y para qué se utiliza?',
        "option_a": 'Una función que genera números aleatorios.',
        "option_b": 'Una función que retorna una secuencia de valores usando yield, consumiendo poca memoria.',
        "option_c": 'Una clase que genera objetos automáticamente.',
        "option_d": 'Un tipo de bucle que genera datos.',
        "correct_answer": 'b',
        "explanation": 'Un generador usa yield para pausar y reanudar ejecución, generando valores bajo demanda (lazy evaluation). Ej: def fib(): a,b=0,1; yield a; yield b; while True: a,b=b,a+b; yield b. Usa O(1) memoria vs lista con O(n).',
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Qué es un decorador en Python y cómo modifica el comportamiento de una función?',
        "option_a": 'Una forma de añadir decoraciones visuales a funciones.',
        "option_b": 'Una función que envuelve otra función, modificando su comportamiento sin cambiar su código.',
        "option_c": 'Un patrón de diseño que solo funciona en clases.',
        "option_d": 'Un tipo de comentario especial.',
        "correct_answer": 'b',
        "explanation": '@decorator envoltura funciones. Ej: @timer mide tiempo de ejecución, @cache cachea resultados. Implementación: def decorator(f): def wrapper(*args, **kwargs): ...; return f(*args, **kwargs); return wrapper. Sintaxis azúcar para funciones de orden superior.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre *args y **kwargs en Python?',
        "option_a": 'args es para argumentos de posición, kwargs para argumentos nombrados.',
        "option_b": 'No hay diferencia; son sinónimos.',
        "option_c": 'kwargs es obsoleto en Python 3.',
        "option_d": 'args solo funciona con números.',
        "correct_answer": 'a',
        "explanation": "*args empaqueta argumentos posicionales en tupla. **kwargs empaqueta argumentos nombrados en diccionario. Ej: def func(*args, **kwargs): print(args); print(kwargs). Llamada: func(1, 2, x=3, y=4) → args=(1,2), kwargs={'x':3, 'y':4}.",
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es polimorfismo en programación orientada a objetos?',
        "option_a": 'La capacidad de un objeto de heredar de múltiples clases.',
        "option_b": 'La capacidad de que objetos de diferentes tipos respondan al mismo mensaje de formas distintas.',
        "option_c": 'La capacidad de ocultamiento de información.',
        "option_d": 'Una función que retorna múltiples valores.',
        "correct_answer": 'b',
        "explanation": "Polimorfismo permite que objetos de clases diferentes respondan a llamadas iguales de manera distinta. Ej: animal.hacer_sonido() en Perro produce 'Guau', en Gato produce 'Miau'. Implementado mediante herencia y sobrescritura de métodos (override).",
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Cuál es la diferencia principal entre composición y herencia en POO?',
        "option_a": 'Composición es más moderna que herencia.',
        "option_b": "Composición permite 'tiene un' relaciones (flexibilidad), herencia es 'es un' (rígido y causa tight coupling).",
        "option_c": 'Herencia es siempre preferible a composición.',
        "option_d": 'No hay diferencia práctica.',
        "correct_answer": 'b',
        "explanation": "Herencia: Perro extends Animal. Composición: Coche tiene Motor. Composición es flexible: puedes cambiar Motor en runtime. Herencia es rígida: cambiar Animal requiere recompilación. Máxima: 'favor composición sobre herencia'.",
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es una clase abstracta y para qué se utiliza?',
        "option_a": 'Una clase que no puede tener instancias, define contrato que subclases deben implementar.',
        "option_b": 'Una clase que es automáticamente abstracta si no tiene variables.',
        "option_c": 'Una clase que abstrahe todo detalle implementación del usuario.',
        "option_d": 'Una clase que solo puede tener métodos abstractos.',
        "correct_answer": 'a',
        "explanation": 'Clase abstracta define métodos abstractos sin implementación. No se puede instanciar (new Animal() falla). Subclases deben implementar métodos. Ej: Animal (abstracta), Perro extends Animal. En Python con abc.ABC.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito del patrón Singleton?',
        "option_a": 'Crear múltiples instancias controladas de una clase.',
        "option_b": 'Garantizar que una clase tenga exactamente una instancia accesible globalmente.',
        "option_c": 'Permitir herencia múltiple de clases.',
        "option_d": 'Separar la creación de objetos de su uso.',
        "correct_answer": 'b',
        "explanation": 'Singleton restringe instancia a una única. Useful para: logger, base de datos, cache. Implementación: constructor privado, método estático getInstance() que retorna instancia única. Desventaja: acoplamiento global, difícil de testear.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre patrones Factory y Builder?',
        "option_a": 'Factory crea objetos simples, Builder crea objetos complejos paso a paso.',
        "option_b": 'No hay diferencia; son sinónimos.',
        "option_c": 'Builder es más antiguo que Factory.',
        "option_d": 'Factory es más lento que Builder.',
        "correct_answer": 'a',
        "explanation": "Factory: método que retorna instancia de clase. Builder: clase que construye objeto paso a paso, permitiendo configuración flexible. Ej: new PersonBuilder().setName('Juan').setAge(30).build(). Factory para creación simple, Builder para construcción compleja.",
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Cuál es el flujo básico de trabajo con Git?',
        "option_a": 'commit → add → push → pull',
        "option_b": 'add → commit → push → pull',
        "option_c": 'pull → add → commit → push',
        "option_d": 'push → add → commit → pull',
        "correct_answer": 'b',
        "explanation": 'Flujo: 1) git add (staging) 2) git commit (guardar localmente) 3) git push (enviar a remoto) 4) git pull (obtener cambios de remoto). Variación para colaboración: pull → cambios → add → commit → push.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre merge y rebase en Git?',
        "option_a": 'Merge es más rápido que rebase.',
        "option_b": 'Merge crea un commit de fusión, rebase reescribe historia moviendo commits.',
        "option_c": 'Rebase es más seguro que merge.',
        "option_d": 'No hay diferencia práctica.',
        "correct_answer": 'b',
        "explanation": 'Merge: git merge feature crea commit de fusión. Rebase: git rebase main reescribe historia de feature sobre main (lineal). Merge preserva historia, rebase la limpia. Usa merge en ramas públicas, rebase en ramas privadas.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Para qué se utiliza .gitignore?',
        "option_a": 'Para ignorar errores de Git.',
        "option_b": 'Para especificar archivos/directorios que Git debe ignorar en commits.',
        "option_c": 'Para configurar permisos de usuarios en repositorio.',
        "option_d": 'Para optimizar la velocidad de clone.',
        "correct_answer": 'b',
        "explanation": '.gitignore contiene patrones de archivos a ignorar (*.log, node_modules/, .env, __pycache__/). Previene commit accidental de archivos temporales, credenciales, dependencias y cachés. Aplica a nuevos archivos; existing tracked files requieren git rm --cached.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es Test Driven Development (TDD)?',
        "option_a": 'Escribir tests después de implementar la funcionalidad.',
        "option_b": 'Escribir tests antes de implementar, luego escribir código que pase los tests.',
        "option_c": 'Usar solo tests unitarios para verificar código.',
        "option_d": 'Un framework para ejecutar tests automáticamente.',
        "correct_answer": 'b',
        "explanation": 'TDD ciclo Red-Green-Refactor: 1) escribir test fallido (red) 2) escribir código mínimo que lo pase (green) 3) refactorizar manteniendo tests verdes. Beneficio: diseño mejor, menos bugs, documentación viva.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito de un test unitario?',
        "option_a": 'Verificar que toda la aplicación funciona correctamente.',
        "option_b": 'Probar funcionalidad de una unidad de código aislada (función, método) con entradas específicas.',
        "option_c": 'Verificar que el servidor está operativo.',
        "option_d": 'Medir la velocidad de ejecución del código.',
        "correct_answer": 'b',
        "explanation": 'Unit test aísla una función/método y verifica comportamiento con casos específicos (happy path, edge cases). Ej: def test_sum(): assert sum([1,2,3]) == 6. Framework: pytest (Python), JUnit (Java). Debería ejecutarse en <100ms.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Qué es mocking en testing y cuándo se utiliza?',
        "option_a": 'Una forma de burlarse del código testeado.',
        "option_b": 'Reemplazar dependencias externas (BD, APIs) con objetos simulados para aislar pruebas unitarias.',
        "option_c": 'Una técnica de optimización de código.',
        "option_d": 'Un estilo de escritura de tests.',
        "correct_answer": 'b',
        "explanation": 'Mock simula comportamiento de dependencias (BD, APIs externas). Ej: en Python from unittest.mock import patch. Permite aislar unit tests, controlar comportamiento externo, y verificar que funciones llaman dependencias correctamente sin conectar realmente.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Cuáles son los cuatro métodos HTTP fundamentales en APIs REST?',
        "option_a": 'SEND, RECEIVE, FETCH, STORE',
        "option_b": 'GET, POST, PUT, DELETE',
        "option_c": 'READ, WRITE, UPDATE, REMOVE',
        "option_d": 'OPEN, CLOSE, MODIFY, CANCEL',
        "correct_answer": 'b',
        "explanation": 'GET: obtener recurso. POST: crear nuevo recurso. PUT: reemplazar recurso completo. DELETE: eliminar recurso. PATCH: actualizar parcialmente. Status: 200 OK, 201 Created, 400 Bad, 401 Unauthorized, 404 Not Found, 500 Server Error.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué código HTTP debe retornar un endpoint al crear un recurso exitosamente?',
        "option_a": '200 OK',
        "option_b": '201 Created',
        "option_c": '204 No Content',
        "option_d": '301 Moved Permanently',
        "correct_answer": 'b',
        "explanation": '201 Created indica éxito en creación de recurso, típicamente incluyendo Location header con URL del recurso creado. 200 OK es para operaciones que retornan datos existentes. 204 No Content para operaciones exitosas sin cuerpo de respuesta.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Cuál es la estructura básica de manejo de excepciones en Python?',
        "option_a": 'try: catch: finally:',
        "option_b": 'try: except: finally:',
        "option_c": 'attempt: error: cleanup:',
        "option_d": 'guard: error:',
        "correct_answer": 'b',
        "explanation": "try: código que puede fallar. except: manejador de excepciones específicas. finally: código que siempre se ejecuta (cleanup). Ej: try: f=open('file'); except FileNotFoundError: print('no existe'); finally: f.close()",
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuáles son los componentes esenciales de una función recursiva correcta?',
        "option_a": 'Caso base (termina recursión) y caso recursivo (llama a sí misma).',
        "option_b": 'Múltiples loops anidados.',
        "option_c": 'Variables globales que modifican estado.',
        "option_d": 'Funciones externas que validan entrada.',
        "correct_answer": 'a',
        "explanation": 'Caso base: condición que detiene recursión. Caso recursivo: llamada a sí misma con problema más pequeño. Ej: factorial(n) = 1 (base si n==0) o n*factorial(n-1). Sin caso base: stack overflow.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es la diferencia entre etiquetas semánticas como <article> y <section> respecto a <div>?',
        "option_a": 'No hay diferencia funcional, solo diferencia visual.',
        "option_b": '<article> y <section> transmiten significado semántico sobre el contenido para SEO y lectores de pantalla.',
        "option_c": '<div> es más moderno que <article> y <section>.',
        "option_d": 'Las etiquetas semánticas solo funcionan en navegadores antiguos.',
        "correct_answer": 'b',
        "explanation": 'Etiquetas semánticas HTML5 (article, section, nav, header, footer) comunican propósito del contenido a máquinas (SEO, screen readers), mejorando accesibilidad e indexación. <div> es genérico sin significado. Siempre prefiere semántica cuando sea posible.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es la función de la etiqueta <header> en HTML5?',
        "option_a": 'Definir los estilos CSS del documento.',
        "option_b": 'Contener la cabecera de sección o página (logo, navegación, título).',
        "option_c": 'Almacenar metadatos del documento.',
        "option_d": 'Definir scripts ejecutables.',
        "correct_answer": 'b',
        "explanation": '<header> agrupa contenido introductorio: logo, navegación, titular. Puede aparecer múltiples veces (header de página, header de artículo). Semánticamente diferente de <head> que contiene metadatos y enlaces a recursos.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito de la etiqueta <figure> y <figcaption>?',
        "option_a": 'Mostrar gráficos matemáticos.',
        "option_b": 'Contener elementos multimedia autónomos (imágenes, diagramas) con leyenda asociada.',
        "option_c": 'Definir figuras CSS.',
        "option_d": 'Reemplazar la etiqueta <img>.',
        "correct_answer": 'b',
        "explanation": "<figure> envuelve contenido autónomo referenciable. <figcaption> añade leyenda descriptiva. Ej: <figure><img src='...'/><figcaption>Diagrama de arquitectura</figcaption></figure>. Semánticamente mejor que div con p para imágenes con leyenda.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuáles son los cuatro componentes del box model de CSS?',
        "option_a": 'Color, borde, margen, padding',
        "option_b": 'Contenido, padding, borde, margen',
        "option_c": 'Altura, anchura, estilo, color',
        "option_d": 'Display, position, z-index, opacity',
        "correct_answer": 'b',
        "explanation": 'Box model de adentro hacia afuera: 1) Contenido (content) 2) Padding (espacio interno) 3) Borde (border) 4) Margen (espacio externo). total_width = content_width + padding*2 + border*2 + margin*2. box-sizing: border-box incluye padding/border en width.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuáles son los valores posibles de la propiedad CSS display?',
        "option_a": 'visible, hidden, transparent',
        "option_b": 'block, inline, inline-block, flex, grid, none',
        "option_c": 'show, hide, display, nodisplay',
        "option_d": 'left, center, right',
        "correct_answer": 'b',
        "explanation": 'display: block (ocupa línea completa), inline (solo espacio necesario), inline-block (hybrid), flex (flexbox), grid (grid layout), none (oculta elemento). Cada valor cambia modelo de layout y comportamiento respecto a hermanos.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cómo se calcula la especificidad de selectores CSS?',
        "option_a": 'Todos los selectores tienen igual especificidad.',
        "option_b": 'Selectores de etiqueta < atributo < clase < ID < estilos inline, permitiendo override de cascada.',
        "option_c": 'La especificidad solo depende de orden en el archivo.',
        "option_d": 'Los ID y clases tienen igual especificidad.',
        "correct_answer": 'b',
        "explanation": 'Especificidad (a,b,c,d): a=inline, b=IDs, c=clases/atributos, d=etiquetas. #id (0,1,0,0) > .clase (0,0,1,0) > div (0,0,0,1). !important fuerza mayor especificidad. Especificidad más alta vence cascada.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es la diferencia entre var, let y const en JavaScript?',
        "option_a": 'Son sinónimos modernos.',
        "option_b": 'var es function-scoped, let/const son block-scoped; const adiciona inmutabilidad.',
        "option_c": 'let y const no pueden reasignarse.',
        "option_d": 'var es más seguro que let y const.',
        "correct_answer": 'b',
        "explanation": 'var: function-scoped, hoisting con undefined. let: block-scoped, hoisting con TDZ (Temporal Dead Zone). const: block-scoped, no reasignación (pero objetos mutable). Usa const por defecto, let si necesitas reasignar.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es hoisting en JavaScript?',
        "option_a": 'Una técnica para optimizar código.',
        "option_b": 'Movimiento conceptual de declaraciones al inicio de scope antes de ejecución.',
        "option_c": 'Un error que debe evitarse.',
        "option_d": 'Un framework de JavaScript.',
        "correct_answer": 'b',
        "explanation": 'var x; es hoisted al top con valor undefined. Código: console.log(x); var x=5; imprime undefined. let/const no se hoizan (TDZ). Causa confusión; evita con let/const y declara variables en top.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cómo se añaden event listeners a elementos DOM en JavaScript?',
        "option_a": "Directamente en HTML con onclick='...'",
        "option_b": 'Con addEventListener() para separar HTML de JavaScript.',
        "option_c": 'Ambos métodos son igualmente recomendados.',
        "option_d": 'Usando jQuery obligatoriamente.',
        "correct_answer": 'b',
        "explanation": "addEventListener() es estándar moderno: element.addEventListener('click', function). Ventajas: separación de concerns, múltiples listeners, remover con removeEventListener(). Evita onclick en HTML por inline scripts.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Para qué se utiliza la Fetch API en JavaScript?',
        "option_a": 'Para acceder al sistema de archivos local.',
        "option_b": 'Para hacer peticiones HTTP/HTTPS a servidores (APIs) de forma asíncrona.',
        "option_c": 'Para manipular el DOM.',
        "option_d": 'Para validar formularios HTML.',
        "correct_answer": 'b',
        "explanation": "Fetch API: fetch('url').then(r => r.json()).then(data => ...). Reemplaza XMLHttpRequest. Retorna Promise que resuelve con Response. Soporta GET, POST, headers, body. CORS debe permitirse.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'hard',
        "text": '¿Qué es una Promesa en JavaScript y cuáles son sus tres estados?',
        "option_a": 'Un objeto que representa un valor futuro con estados: pending, resolved, rejected.',
        "option_b": 'Un tipo de bucle asíncrono.',
        "option_c": 'Un comentario que documenta intención del código.',
        "option_d": 'Un método para validar entrada de usuario.',
        "correct_answer": 'a',
        "explanation": 'Promise: pending (inicial) → resolved (cumplida) o rejected (rechazada). Ej: new Promise((resolve, reject) => { if(ok) resolve(value); else reject(error); }).then(...).catch(...). Facilita manejo de código asíncrono vs callbacks anidados.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es la estructura general de un mensaje HTTP?',
        "option_a": 'URL, puerto, protocolo',
        "option_b": 'Línea de solicitud/estado, headers, cuerpo (body)',
        "option_c": 'Solo método HTTP',
        "option_d": 'Información del navegador',
        "correct_answer": 'b',
        "explanation": 'HTTP Request: línea (GET /path HTTP/1.1), headers (Host, Content-Type), línea vacía, body (opcional). HTTP Response: línea de estado (HTTP/1.1 200 OK), headers, línea vacía, body. Headers: Content-Type, Authorization, Cache-Control, etc.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es la principal diferencia entre REST y SOAP?',
        "option_a": 'REST es más nuevo que SOAP.',
        "option_b": 'REST usa HTTP methods y JSON/XML, SOAP usa XML-RPC con envelopes complejos.',
        "option_c": 'SOAP es simplemente REST con XML.',
        "option_d": 'No hay diferencia arquitectónica.',
        "correct_answer": 'b',
        "explanation": 'REST: arquitectural, stateless, usa GET/POST/PUT/DELETE en recursos. SOAP: protocolo RPC basado en XML con wsdl, envelopes complejos, estado. REST es más ligero, flexible, prevalente hoy. SOAP prevalente en enterprise legacy.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es CORS (Cross-Origin Resource Sharing) y por qué es importante?',
        "option_a": 'Un protocolo de seguridad para encriptar datos.',
        "option_b": 'Un mecanismo que permite peticiones cross-origin desde navegadores de forma segura.',
        "option_c": 'Un método HTTP adicional.',
        "option_d": 'Un tipo de sesión de usuario.',
        "correct_answer": 'b',
        "explanation": 'CORS es header HTTP que autoriza peticiones desde origin diferente. Navegadores bloquean por defecto (same-origin policy). Server retorna Access-Control-Allow-Origin: *. Previene CSRF. Servidor debe explícitamente permitir origins.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es la sintaxis correcta para un objeto JSON?',
        "option_a": "{name: 'Juan', age: 30}",
        "option_b": '{"name": "Juan", "age": 30}',
        "option_c": "{name='Juan', age=30}",
        "option_d": '<name>Juan</name><age>30</age>',
        "correct_answer": 'b',
        "explanation": 'JSON requiere comillas dobles en claves y strings. Tipos: número, string (comillas), booleano (true/false), null, array, objeto. JSON.parse() convierte string JSON a objeto JavaScript. JSON.stringify() hace lo inverso.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre JSON y XML?',
        "option_a": 'JSON es más nuevo y más compacto; XML es más verboso.',
        "option_b": 'XML solo se usa en bases de datos; JSON solo en APIs.',
        "option_c": 'No hay diferencia práctica.',
        "option_d": 'JSON puede contener código ejecutable; XML no.',
        "correct_answer": 'a',
        "explanation": "JSON: {name: 'Juan'} vs XML: <person><name>Juan</name></person>. JSON es más ligero, legible, parseable en JS nativamente. XML es más descriptivo, soporta atributos, esquemas (XSD). Hoy JSON prevalece en APIs; XML en SOAP, documentos.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito de justify-content en Flexbox?',
        "option_a": 'Controlar alineación vertical de items.',
        "option_b": 'Distribuir espacio horizontal entre items en flex container.',
        "option_c": 'Definir el tamaño de items.',
        "option_d": 'Cambiar el orden de items.',
        "correct_answer": 'b',
        "explanation": 'justify-content: flex-start (izquierda), center (centro), space-between, space-around, space-evenly. Ej: .container { display: flex; justify-content: center; }. align-items controla alineación vertical.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cómo se define un grid básico con CSS Grid?',
        "option_a": '.grid { display: grid; grid-template-columns: 1fr 1fr 1fr; }',
        "option_b": '.grid { layout: grid-3; }',
        "option_c": '.grid { display: flex; }',
        "option_d": '.grid { grid: 3 columns; }',
        "correct_answer": 'a',
        "explanation": 'CSS Grid: display: grid; grid-template-columns: define columnas (1fr = una fracción igual). grid-template-rows define filas. gap: espaciado. Más poderoso que flexbox para layouts 2D complejos.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Por qué es importante incluir atributo alt en imágenes HTML?',
        "option_a": 'Para mejorar velocidad de carga.',
        "option_b": 'Para proporcionar descripción accesible a lectores de pantalla y SEO.',
        "option_c": 'Para definir título de imagen.',
        "option_d": 'Para reemplazar el src.',
        "correct_answer": 'b',
        "explanation": "alt proporciona descripción de imagen para: usuarios con discapacidad visual (screen readers), navegadores que no cargan imagen, SEO. Buena práctica: alt='Diagrama de arquitectura de sistema', no alt='imagen' o alt=''.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué son ARIA labels y cuándo se utilizan?',
        "option_a": 'Etiquetas HTML para definir estilos.',
        "option_b": 'Atributos que proporcionan información accesible para lectores de pantalla cuando HTML no es suficiente.',
        "option_c": 'Un framework de JavaScript.',
        "option_d": 'Un protocolo de seguridad.',
        "correct_answer": 'b',
        "explanation": "ARIA (Accessible Rich Internet Applications): aria-label, aria-labelledby, aria-description. Ej: <button aria-label='Cerrar menú'>×</button>. Complementa HTML semántico para componentes complejos (sliders, modales) que no tienen etiqueta HTML nativa.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": "¿Cuál es la diferencia entre input type='text' e input type='email'?",
        "option_a": 'Solo diferencia visual.',
        "option_b": "type='email' proporciona validación de formato email y teclado móvil optimizado.",
        "option_c": "type='email' solo funciona en navegadores antiguos.",
        "option_d": 'No hay diferencia.',
        "correct_answer": 'b',
        "explanation": "input type='email' valida automáticamente formato (x@y.z), muestra teclado con @ en móviles, soporta multiple attribute. type='text' no valida. HTML5 input types: email, password, number, date, checkbox, radio, file, range, color.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Para qué sirve el atributo enctype en formularios HTML?',
        "option_a": 'Para encriptar datos del formulario.',
        "option_b": 'Para especificar cómo se codifican los datos al enviar (multipart/form-data para archivos).',
        "option_c": 'Para definir método POST.',
        "option_d": 'Para validar entrada de usuario.',
        "correct_answer": 'b',
        "explanation": "enctype: application/x-www-form-urlencoded (defecto, strings), multipart/form-data (archivos), text/plain. <form enctype='multipart/form-data'><input type='file'></form> para upload.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es el propósito de la meta tag charset?',
        "option_a": 'Definir el idioma del documento.',
        "option_b": 'Especificar la codificación de caracteres (UTF-8) del documento HTML.',
        "option_c": 'Definir el viewport.',
        "option_d": 'Establecer el color de fondo.',
        "correct_answer": 'b',
        "explanation": "<meta charset='UTF-8'> debe estar en <head> primero. UTF-8 soporta todos los caracteres mundiales. Sin declaración, navegador intenta adivinar (riesgoso). Importante para caracteres acentuados, CJK, emoji.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Para qué se utiliza la meta tag viewport?',
        "option_a": 'Para definir el tamaño de fuente.',
        "option_b": 'Para instruir al navegador sobre dimensiones iniciales y escala en dispositivos móviles.',
        "option_c": 'Para definir el color de la barra de dirección.',
        "option_d": 'Para especificar el servidor a conectar.',
        "correct_answer": 'b',
        "explanation": "<meta name='viewport' content='width=device-width, initial-scale=1'> es esencial para responsive design. Sin esto, navegadores móviles simulan viewport de escritorio (980px), causando zoom. Permite zooming user-scalable=yes/no.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Cuál es el propósito de Open Graph meta tags?',
        "option_a": 'Para graficar datos estadísticos.',
        "option_b": 'Para definir cómo aparece el contenido cuando se comparte en redes sociales.',
        "option_c": 'Para mejorar velocidad de carga.',
        "option_d": 'Para definir fuentes personalizadas.',
        "correct_answer": 'b',
        "explanation": "Open Graph: <meta property='og:title' content='...'>, og:image, og:url, og:description. Redes sociales (Facebook, Twitter) usan estas tags para mostrar preview al compartir. Twitter usa card meta tags (twitter:card, twitter:image).",
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'easy',
        "text": '¿Qué es un ataque de denegación de servicio (DDoS)?',
        "option_a": 'Un ataque que roba credenciales de usuario.',
        "option_b": 'Un ataque que inunda un servidor/red con tráfico masivo para hacerlo inaccesible.',
        "option_c": 'Un virus que destruye datos.',
        "option_d": 'Un protocolo de comunicación segura.',
        "correct_answer": 'b',
        "explanation": 'DDoS (Distributed Denial of Service) usa botnets para enviar millones de peticiones desde múltiples IPs, agotando ancho de banda o recursos del servidor. Diferente de DoS (desde una IP). Mitigation: rate limiting, WAF, CDN scrubbing.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es un ataque Man-in-the-Middle (MITM) y cómo protegerse?',
        "option_a": 'Un virus que se interpone entre archivos.',
        "option_b": 'Un ataque donde el adversario intercepta comunicación entre dos partes para robar o modificar datos.',
        "option_c": 'Un error de configuración del servidor.',
        "option_d": 'Un protocolo de encriptación débil.',
        "correct_answer": 'b',
        "explanation": 'MITM permite atacante sniffear credenciales y datos. Protección: usar HTTPS/TLS (cifrado end-to-end), verificar certificados, VPN, no usar WiFi abierto. PKI pinning previene MITM con certificados falsos.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es AppArmor en sistemas Linux?',
        "option_a": 'Una herramienta para compilar aplicaciones.',
        "option_b": 'Un módulo de control de acceso obligatorio (MAC) que limita permisos de aplicaciones.',
        "option_c": 'Un firewall de aplicación.',
        "option_d": 'Un gestor de paquetes.',
        "correct_answer": 'b',
        "explanation": 'AppArmor limita permisos de programas mediante profiles. Similar a SELinux pero más simple. Ej: permitir nginx acceso solo a /var/www, /etc/nginx. Complementa permisos Unix. En Debian/Ubuntu por defecto.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'hard',
        "text": '¿Qué es una vulnerabilidad IDOR (Insecure Direct Object Reference)?',
        "option_a": 'Un error en la base de datos.',
        "option_b": 'Cuando una aplicación expone referencias a objetos internos sin validar acceso, permitiendo acceso no autorizado.',
        "option_c": 'Un protocolo de autenticación débil.',
        "option_d": 'Un malware específico.',
        "correct_answer": 'b',
        "explanation": 'IDOR: endpoint /user/profile/123 muestra perfil del usuario 123. Atacante cambia a 124 y accede perfil otro usuario sin autorización. Fix: validar que usuario solo accede sus propios objetos. Es #6 en OWASP Top 10.',
    },
    {
        "subject": 'Ciberseguridad',
        "difficulty": 'medium',
        "text": '¿Qué es una vulnerabilidad de Security Misconfiguration?',
        "option_a": 'Un error de programación en el código fuente.',
        "option_b": 'Configuración insegura de servidores, frameworks (debug enabled, defaults no cambiados, headers faltantes).',
        "option_c": 'Un ataque de fuerza bruta.',
        "option_d": 'Un tipo de malware.',
        "correct_answer": 'b',
        "explanation": 'Security Misconfiguration: servidor con debug habilitado, password por defecto de admin, no actualizado, headers de seguridad faltantes (X-Frame-Options, CSP), directorios públicos listables. #5 OWASP Top 10.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es un patrón Observer en diseño de software?',
        "option_a": 'Un patrón que observa errores en tiempo de ejecución.',
        "option_b": 'Un patrón donde objetos se suscriben a cambios de un sujeto para ser notificados automáticamente.',
        "option_c": 'Un tipo de estructura de datos.',
        "option_d": 'Una herramienta de debugging.',
        "correct_answer": 'b',
        "explanation": 'Observer: sujeto (Subject) notifica automáticamente observadores (Observers) cuando cambia estado. Desacoplamiento entre sujeto y observadores. Usado en: eventos UI, pub/sub systems, reactive programming.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es el propósito del patrón Strategy?',
        "option_a": 'Una estrategia para ganar en videojuegos.',
        "option_b": 'Encapsular familia de algoritmos intercambiables sin cambiar cliente.',
        "option_c": 'Un patrón de creación de objetos.',
        "option_d": 'Un tipo de estructura de datos.',
        "correct_answer": 'b',
        "explanation": 'Strategy: define interfaz común para algoritmos (ej: ordenamiento). Contexto usa estrategia sin conocer detalles. Ej: Sort(QuickSort), Sort(MergeSort). Permite elegir algoritmo en runtime. Similar a polimorfismo.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'easy',
        "text": '¿Qué es el versionado semántico (semver)?',
        "option_a": 'Un protocolo de red.',
        "option_b": 'Formato de versión MAJOR.MINOR.PATCH indicando compatibilidad (1.2.3).',
        "option_c": 'Un lenguaje de marcado.',
        "option_d": 'Un tipo de hash criptográfico.',
        "correct_answer": 'b',
        "explanation": 'Semver: MAJOR (incompatible), MINOR (compatible hacia atrás), PATCH (bugfix). v1.2.3 → v1.3.0 (features) vs v2.0.0 (breaking). Usado en npm, pip, rubygems. Facilita gestión de dependencias.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es memoización en programación?',
        "option_a": 'Un método para memorizar código.',
        "option_b": 'Cachear resultados de funciones costosas para evitar recálculo.',
        "option_c": 'Una técnica de compilación.',
        "option_d": 'Un tipo de variable global.',
        "correct_answer": 'b',
        "explanation": 'Memoización: cachea resultado de función basado en argumentos. Próxima llamada con argumentos iguales retorna valor cacheado. Ej: factorial(n) recalculado sin cachear. Con memoización: fibonacci(5) evita cálculo exponencial. Requiere función pura.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'hard',
        "text": '¿Qué es Big-O notation y por qué es importante en algoritmos?',
        "option_a": 'Una notación matemática para expresar el tamaño de variables.',
        "option_b": 'Notación que describe cómo crece el tiempo/espacio de algoritmo con tamaño de entrada.',
        "option_c": 'Un operador de comparación en lenguajes de programación.',
        "option_d": 'Un acrónimo de seguridad informática.',
        "correct_answer": 'b',
        "explanation": 'Big-O ignora constantes y terms menores. O(2n+5) = O(n). O(n²+n) = O(n²). Permite comparar algoritmos independientemente de hardware. O(1)<O(log n)<O(n)<O(n log n)<O(n²)<O(2ⁿ)<O(n!)',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Qué es un grafo en estructuras de datos?',
        "option_a": 'Una representación visual de datos estadísticos.',
        "option_b": 'Una estructura con nodos (vértices) conectados por aristas, representando relaciones.',
        "option_c": 'Un tipo de array multidimensional.',
        "option_d": 'Un árbol binario especializado.',
        "correct_answer": 'b',
        "explanation": 'Grafo: nodos (vértices) y aristas (conexiones). Dirigido (aristas con dirección) o no dirigido. Ponderado (aristas con peso) o no ponderado. Usado en: redes, mapas, recomendaciones. Algoritmos: DFS, BFS, Dijkstra, Floyd-Warshall.',
    },
    {
        "subject": 'Programación',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre tipado estático y dinámico?',
        "option_a": 'Los lenguajes tipados estáticos son más modernos.',
        "option_b": 'Estático: tipos verificados en compile-time (Java, C++). Dinámico: tipos en runtime (Python, JavaScript).',
        "option_c": 'Dinámico es siempre más rápido.',
        "option_d": 'No hay diferencia práctica.',
        "correct_answer": 'b',
        "explanation": 'Tipado estático: errores de tipo detectados antes de ejecutar, mayor seguridad. Dinámico: mayor flexibilidad, pero errores en runtime. Type hints en Python acercan tipado dinámico a estático.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Qué es Bootstrap en desarrollo web?',
        "option_a": 'Un proceso de inicio de servidor.',
        "option_b": 'Un framework CSS para crear interfaces responsive rápidamente.',
        "option_c": 'Un lenguaje de programación.',
        "option_d": 'Un protocolo de seguridad.',
        "correct_answer": 'b',
        "explanation": 'Bootstrap: framework con componentes (botones, alerts, modales), grid system (12 columnas), clases utilitarias. Facilita desarrollo responsive. Clases: btn, card, navbar, container. Alternativas: Tailwind, Material Design.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre async y defer en etiquetas <script>?',
        "option_a": 'Ambos son sinónimos.',
        "option_b": 'async descarga en paralelo sin bloquear, ejecuta apenas esté listo. defer ejecuta después del DOM.',
        "option_c": 'defer es más antiguo que async.',
        "option_d": 'async solo funciona en módulos ES6.',
        "correct_answer": 'b',
        "explanation": 'Sin atributo: script bloquea parsing HTML. async: descarga paralela, ejecuta cuando lista (puede antes de DOM). defer: descarga paralela, ejecuta después de DOM en orden. Prefer defer para scripts dependientes.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es XML y cuál es su diferencia principal con JSON?',
        "option_a": 'XML es una base de datos; JSON es un lenguaje de consulta.',
        "option_b": 'XML es más verboso con tags; JSON es más compacto con pares clave-valor.',
        "option_c": 'JSON es más antiguo que XML.',
        "option_d": 'No hay diferencia técnica.',
        "correct_answer": 'b',
        "explanation": "XML: <person><name>Juan</name></person>. JSON: {name: 'Juan'}. XML soporta atributos, namespaces, DTD. JSON es subset de JavaScript, parseable nativamente en JS. Hoy JSON prevalece; XML usado en SOAP, configuración, documentos.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'hard',
        "text": '¿Qué es XPath en XML?',
        "option_a": 'Un protocolo para transferir archivos XML.',
        "option_b": 'Un lenguaje de query para seleccionar nodos en documentos XML.',
        "option_c": 'Una herramienta para validar XML.',
        "option_d": 'Un estándar de encriptación.',
        "correct_answer": 'b',
        "explanation": "XPath: /root/person[1]/name selecciona nombre de primer person. Usar en navegadores, servidores, testing. Similar a CSS selectors pero más poderoso. Ej: //person[@id='1'] selecciona person con atributo id=1.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es YAML y dónde se utiliza comúnmente?',
        "option_a": 'Un lenguaje de programación.',
        "option_b": 'Un formato legible para datos y configuración (Docker, CI/CD, Kubernetes).',
        "option_c": 'Un protocolo de encriptación.',
        "option_d": 'Una base de datos NoSQL.',
        "correct_answer": 'b',
        "explanation": 'YAML: sintaxis con indentación, sin comillas. Tipos: strings, números, booleans, listas, dicts. Usado en docker-compose.yml, .github/workflows, Kubernetes manifests. Ventaja: legible; desventaja: sensible a espacios.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuáles son los códigos HTTP más importantes y su significado?',
        "option_a": 'Solo existen dos: 200 y 404.',
        "option_b": '200 OK, 201 Created, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 500 Server Error.',
        "option_c": 'Los códigos varían según navegador.',
        "option_d": 'No hay diferencia entre 4xx y 5xx.',
        "correct_answer": 'b',
        "explanation": 'Códigos HTTP: 1xx informativo, 2xx éxito, 3xx redirección, 4xx error cliente, 5xx error servidor. 200: petición exitosa. 401: autenticación requerida. 403: acceso denegado. 404: no encontrado. 500: error interno servidor.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es Content Security Policy (CSP)?',
        "option_a": 'Una política de privacidad de contenido.',
        "option_b": 'Un header HTTP que controla qué recursos (scripts, estilos) puede cargar una página.',
        "option_c": 'Un protocolo de encriptación.',
        "option_d": 'Un framework de seguridad.',
        "correct_answer": 'b',
        "explanation": "CSP mitiga XSS y code injection. Ej: Content-Security-Policy: default-src 'self' permite solo scripts/estilos del mismo origin. Puede especificar: script-src, style-src, img-src. Stricto CSP bloquea inline scripts.",
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'easy',
        "text": '¿Qué es un sitemap.xml y cuál es su propósito?',
        "option_a": 'Un archivo CSS para estilos.',
        "option_b": 'Un archivo XML que lista URLs del sitio para SEO, permitiendo a buscadores indexar eficientemente.',
        "option_c": 'Un mapa visual del sitio.',
        "option_d": 'Un archivo de configuración del servidor.',
        "correct_answer": 'b',
        "explanation": 'sitemap.xml: listado de todas las URLs con metadata (lastmod, changefreq, priority). Ubicado en root. Declara en robots.txt: Sitemap: https://example.com/sitemap.xml. Ayuda a Google a descubrir páginas, especialmente dinámicas.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Qué es un robots.txt y qué instrucciones contiene?',
        "option_a": 'Un archivo que ejecuta robots.',
        "option_b": 'Un archivo de texto que instruye a bots de búsqueda qué páginas indexar/no indexar.',
        "option_c": 'Un protocolo de comunicación.',
        "option_d": 'Un archivo de configuración de seguridad.',
        "correct_answer": 'b',
        "explanation": 'robots.txt en root contiene: User-agent: * (todos bots), Disallow: /admin (no indexar /admin), Allow: /admin/public. No es mandatorio; bots honestos respetan, pero maliciosos lo ignoran.',
    },
    {
        "subject": 'Lenguaje de Marcas',
        "difficulty": 'medium',
        "text": '¿Cuál es la diferencia entre HTTP/1.1 e HTTP/2?',
        "option_a": 'HTTP/2 es solo para HTTPS.',
        "option_b": 'HTTP/2 multiplex múltiples streams en una conexión, comprime headers, mejora rendimiento.',
        "option_c": 'HTTP/1.1 es más rápido que HTTP/2.',
        "option_d": 'No hay diferencia práctica.',
        "correct_answer": 'b',
        "explanation": 'HTTP/1.1: conexión por request (overhead). HTTP/2: multiplex (múltiples requests/responses simultáneamente), compresión HPACK, Server Push. Reduce latencia. Requiere HTTPS. HTTP/3 usa QUIC.',
    },
]



def seed():
    db = SessionLocal()
    try:
        existing = {q.text.strip().lower() for q in db.query(Question).all()}
        inserted_by_subject = {}

        for q in QUESTIONS:
            if q['text'].strip().lower() in existing:
                continue

            subject = q['subject']
            db.add(Question(
                subject        = q['subject'],
                difficulty     = q['difficulty'],
                text           = q['text'],
                option_a       = q['option_a'],
                option_b       = q['option_b'],
                option_c       = q['option_c'],
                option_d       = q['option_d'],
                correct_answer = q['correct_answer'],
                explanation    = q['explanation'],
                approved       = True,
            ))
            existing.add(q['text'].strip().lower())
            inserted_by_subject[subject] = inserted_by_subject.get(subject, 0) + 1

        db.commit()
        print("\n" + "="*70)
        print("SEED: Nuevas preguntas - Ciberseguridad, Programación, Lenguaje de Marcas")
        print("="*70)
        for subject, count in sorted(inserted_by_subject.items()):
            print(f"  ✓ {subject}: {count} preguntas")
        total = sum(inserted_by_subject.values())
        print(f"\n  Total insertadas: {total} preguntas nuevas")
        print("="*70 + "\n")

    except Exception as e:
        db.rollback()
        print(f"\n✗ Error: {e}\n")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
