"""initial schema

Revision ID: 0950c7663e42
Revises: 
Create Date: 2026-03-13 21:33:43.987798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0950c7663e42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_group_members_group_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_class_group_members_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_class_group_members_user_id'), table_name='class_group_members')
    op.drop_index(op.f('ix_group_member_unique'), table_name='class_group_members')
    op.drop_table('class_group_members')
    
    op.drop_index(op.f('ix_group_assignment_unique'), table_name='group_assignments')
    op.drop_index(op.f('ix_group_assignments_group_id'), table_name='group_assignments')
    op.drop_index(op.f('ix_group_assignments_id'), table_name='group_assignments')
    op.drop_table('group_assignments')
    
    op.drop_index(op.f('ix_group_module_unique'), table_name='group_modules')
    op.drop_index(op.f('ix_group_modules_group_id'), table_name='group_modules')
    op.drop_index(op.f('ix_group_modules_id'), table_name='group_modules')
    op.drop_table('group_modules')
    
    op.drop_index(op.f('ix_class_assignments_group_id'), table_name='class_assignments')
    op.drop_index(op.f('ix_class_assignments_id'), table_name='class_assignments')
    op.drop_table('class_assignments')
    
    op.drop_index(op.f('ix_class_groups_docente_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_id'), table_name='class_groups')
    op.drop_table('class_groups')
    
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_education_leads_email'), table_name='education_leads')
    op.drop_index(op.f('ix_education_leads_id'), table_name='education_leads')
    op.drop_table('education_leads')
    op.drop_index(op.f('ix_docente_orders_id'), table_name='docente_orders')
    op.drop_index(op.f('ix_docente_orders_paypal_order_id'), table_name='docente_orders')
    op.drop_table('docente_orders')
    op.add_column('coupons', sa.Column('description', sa.String(), nullable=True))
    op.add_column('coupons', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('coupons', sa.Column('applicable_plans', sa.String(), nullable=True))
    op.drop_column('questions', 'approved')
    op.alter_column('sql_exercises', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('terminal_labs', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('theory_posts', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('theory_posts', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_user_errors_question_id'), 'user_errors', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_errors_user_id'), 'user_errors', ['user_id'], unique=False)
    op.create_index('ix_user_errors_user_question', 'user_errors', ['user_id', 'question_id'], unique=False)
    op.create_index(op.f('ix_user_lab_completions_lab_id'), 'user_lab_completions', ['lab_id'], unique=False)
    op.create_index(op.f('ix_user_lab_completions_user_id'), 'user_lab_completions', ['user_id'], unique=False)
    op.create_index('ix_user_lab_completions_user_lab', 'user_lab_completions', ['user_id', 'lab_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index('ix_user_progress_user_subject', 'user_progress', ['user_id', 'subject'], unique=False)
    op.drop_column('users', 'docente_license_total')
    op.drop_column('users', 'docente_plan_expires')
    op.drop_column('users', 'docente_plan_key')
    op.drop_column('users', 'pilot_approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pilot_approval_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('docente_plan_key', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('docente_plan_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('docente_license_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index('ix_user_progress_user_subject', table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index('ix_user_lab_completions_user_lab', table_name='user_lab_completions')
    op.drop_index(op.f('ix_user_lab_completions_user_id'), table_name='user_lab_completions')
    op.drop_index(op.f('ix_user_lab_completions_lab_id'), table_name='user_lab_completions')
    op.drop_index('ix_user_errors_user_question', table_name='user_errors')
    op.drop_index(op.f('ix_user_errors_user_id'), table_name='user_errors')
    op.drop_index(op.f('ix_user_errors_question_id'), table_name='user_errors')
    op.alter_column('theory_posts', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('theory_posts', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('terminal_labs', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sql_exercises', 'is_free',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('questions', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('coupons', 'applicable_plans')
    op.drop_column('coupons', 'expires_at')
    op.drop_column('coupons', 'description')
    op.create_table('group_modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['class_groups.id'], name=op.f('group_modules_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('group_modules_pkey'))
    )
    op.create_index(op.f('ix_group_modules_id'), 'group_modules', ['id'], unique=False)
    op.create_index(op.f('ix_group_modules_group_id'), 'group_modules', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_module_unique'), 'group_modules', ['group_id', 'module_name'], unique=True)
    op.create_table('group_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['class_groups.id'], name=op.f('group_assignments_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('group_assignments_pkey'))
    )
    op.create_index(op.f('ix_group_assignments_id'), 'group_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_group_assignments_group_id'), 'group_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_assignment_unique'), 'group_assignments', ['group_id', 'module_type'], unique=True)
    op.create_table('docente_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paypal_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('license_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('docente_orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('docente_orders_pkey'))
    )
    op.create_index(op.f('ix_docente_orders_paypal_order_id'), 'docente_orders', ['paypal_order_id'], unique=True)
    op.create_index(op.f('ix_docente_orders_id'), 'docente_orders', ['id'], unique=False)
    op.create_table('education_leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('students', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('usage_type', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('last_contacted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_followup_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('education_leads_pkey'))
    )
    op.create_index(op.f('ix_education_leads_id'), 'education_leads', ['id'], unique=False)
    op.create_index(op.f('ix_education_leads_email'), 'education_leads', ['email'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['education_leads.id'], name=op.f('lead_activities_lead_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lead_activities_pkey'))
    )
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('lead_notes_author_id_fkey')),
    sa.ForeignKeyConstraint(['lead_id'], ['education_leads.id'], name=op.f('lead_notes_lead_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lead_notes_pkey'))
    )
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_table('class_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['class_groups.id'], name=op.f('class_assignments_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('class_assignments_pkey'))
    )
    op.create_index(op.f('ix_class_assignments_id'), 'class_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_class_assignments_group_id'), 'class_assignments', ['group_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('docente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invite_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('license_count', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['users.id'], name=op.f('class_groups_docente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('class_groups_pkey'))
    )
    op.create_index(op.f('ix_class_groups_id'), 'class_groups', ['id'], unique=False)
    op.create_index(op.f('ix_class_groups_docente_id'), 'class_groups', ['docente_id'], unique=False)
    op.create_table('class_group_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['class_groups.id'], name=op.f('class_group_members_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('class_group_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('class_group_members_pkey'))
    )
    op.create_index(op.f('ix_group_member_unique'), 'class_group_members', ['group_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_class_group_members_user_id'), 'class_group_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_class_group_members_id'), 'class_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_class_group_members_group_id'), 'class_group_members', ['group_id'], unique=False)
    # ### end Alembic commands ###
