"""add daily xp cap fields

Revision ID: 2e1bbc3dabee
Revises: 0950c7663e42
Create Date: 2026-03-13 21:37:19.089957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1bbc3dabee'
down_revision: Union[str, Sequence[str], None] = '0950c7663e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_xp_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('xp_today', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp_today')
    op.drop_column('users', 'last_xp_date')
    # ### end Alembic commands ###
