"""add processed stripe events table

Revision ID: stripe_idempotency_001
Revises: f3a8d2e1c9b7
Create Date: 2026-03-19 19:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'stripe_idempotency_001'
down_revision = 'f3a8d2e1c9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stripe_event_id', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_stripe_events_id'), 'processed_stripe_events', ['id'], unique=False)
    op.create_index(op.f('ix_processed_stripe_events_stripe_event_id'), 'processed_stripe_events', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_stripe_events_stripe_event_id'), table_name='processed_stripe_events')
    op.drop_index(op.f('ix_processed_stripe_events_id'), table_name='processed_stripe_events')
    op.drop_table('processed_stripe_events')
    # ### end Alembic commands ###
